import {
  JobPosting,
  SkillTrend,
  GeoTalentHub,
  AzureCertProfile,
  HistoricalTrendPoint,
  MacroMarketStats
} from '../types/market';

export const macroStats: MacroMarketStats = {
  totalActiveJobs: 2481920,
  yoyHiringGrowth: 14.8,
  avgTechSalary: 146800,
  remotePercent: 38.4,
  hybridPercent: 44.2,
  onsitePercent: 17.4,
  avgTimeToFillDays: 34,
  totalCompaniesHiring: 68420,
  azureSkillMarketShare: 41.2, // % of enterprise cloud listings mentioning Azure stacks
  lastUpdated: 'Live Continuous Ingestion (Azure Event Hubs)'
};

export const historicalTrends: HistoricalTrendPoint[] = [
  { yearQuarter: '2022 Q1', aiMlDemand: 45, cloudDevOpsDemand: 78, cybersecurityDemand: 58, dataEngineeringDemand: 62, fullstackDemand: 88, layoffsIndex: 12, medianTechSalary: 128000 },
  { yearQuarter: '2022 Q2', aiMlDemand: 48, cloudDevOpsDemand: 82, cybersecurityDemand: 60, dataEngineeringDemand: 65, fullstackDemand: 90, layoffsIndex: 25, medianTechSalary: 131000 },
  { yearQuarter: '2022 Q3', aiMlDemand: 52, cloudDevOpsDemand: 84, cybersecurityDemand: 63, dataEngineeringDemand: 68, fullstackDemand: 86, layoffsIndex: 48, medianTechSalary: 132500 },
  { yearQuarter: '2022 Q4', aiMlDemand: 58, cloudDevOpsDemand: 80, cybersecurityDemand: 65, dataEngineeringDemand: 67, fullstackDemand: 78, layoffsIndex: 85, medianTechSalary: 130000 },
  { yearQuarter: '2023 Q1', aiMlDemand: 69, cloudDevOpsDemand: 79, cybersecurityDemand: 68, dataEngineeringDemand: 70, fullstackDemand: 72, layoffsIndex: 110, medianTechSalary: 132000 },
  { yearQuarter: '2023 Q2', aiMlDemand: 78, cloudDevOpsDemand: 83, cybersecurityDemand: 71, dataEngineeringDemand: 73, fullstackDemand: 74, layoffsIndex: 75, medianTechSalary: 135000 },
  { yearQuarter: '2023 Q3', aiMlDemand: 84, cloudDevOpsDemand: 86, cybersecurityDemand: 74, dataEngineeringDemand: 76, fullstackDemand: 77, layoffsIndex: 52, medianTechSalary: 137500 },
  { yearQuarter: '2023 Q4', aiMlDemand: 89, cloudDevOpsDemand: 88, cybersecurityDemand: 77, dataEngineeringDemand: 80, fullstackDemand: 80, layoffsIndex: 42, medianTechSalary: 139000 },
  { yearQuarter: '2024 Q1', aiMlDemand: 94, cloudDevOpsDemand: 90, cybersecurityDemand: 81, dataEngineeringDemand: 84, fullstackDemand: 82, layoffsIndex: 38, medianTechSalary: 141000 },
  { yearQuarter: '2024 Q2', aiMlDemand: 98, cloudDevOpsDemand: 92, cybersecurityDemand: 84, dataEngineeringDemand: 87, fullstackDemand: 84, layoffsIndex: 28, medianTechSalary: 143000 },
  { yearQuarter: '2024 Q3', aiMlDemand: 104, cloudDevOpsDemand: 94, cybersecurityDemand: 86, dataEngineeringDemand: 89, fullstackDemand: 85, layoffsIndex: 22, medianTechSalary: 144500 },
  { yearQuarter: '2024 Q4', aiMlDemand: 112, cloudDevOpsDemand: 96, cybersecurityDemand: 89, dataEngineeringDemand: 92, fullstackDemand: 87, layoffsIndex: 18, medianTechSalary: 146000 },
  { yearQuarter: '2025 Q1', aiMlDemand: 124, cloudDevOpsDemand: 99, cybersecurityDemand: 92, dataEngineeringDemand: 95, fullstackDemand: 89, layoffsIndex: 14, medianTechSalary: 148500 },
  { yearQuarter: '2025 Q2', aiMlDemand: 138, cloudDevOpsDemand: 103, cybersecurityDemand: 95, dataEngineeringDemand: 98, fullstackDemand: 91, layoffsIndex: 12, medianTechSalary: 151000 },
  { yearQuarter: '2025 Q3', aiMlDemand: 152, cloudDevOpsDemand: 107, cybersecurityDemand: 98, dataEngineeringDemand: 102, fullstackDemand: 93, layoffsIndex: 11, medianTechSalary: 153500 },
  { yearQuarter: '2025 Q4', aiMlDemand: 165, cloudDevOpsDemand: 112, cybersecurityDemand: 101, dataEngineeringDemand: 105, fullstackDemand: 95, layoffsIndex: 10, medianTechSalary: 156000 },
  { yearQuarter: '2026 Q1', aiMlDemand: 178, cloudDevOpsDemand: 118, cybersecurityDemand: 105, dataEngineeringDemand: 109, fullstackDemand: 97, layoffsIndex: 9, medianTechSalary: 159000 },
  { yearQuarter: '2026 Q2 (Est)', aiMlDemand: 192, cloudDevOpsDemand: 124, cybersecurityDemand: 109, dataEngineeringDemand: 114, fullstackDemand: 99, layoffsIndex: 8, medianTechSalary: 162000 },
  { yearQuarter: '2026 Q3 (Est)', aiMlDemand: 208, cloudDevOpsDemand: 130, cybersecurityDemand: 113, dataEngineeringDemand: 118, fullstackDemand: 102, layoffsIndex: 8, medianTechSalary: 165000 }
];

export const skillTrendsData: SkillTrend[] = [
  {
    id: 'azure-openai',
    name: 'Azure OpenAI & AI Studio',
    category: 'AI & Machine Learning',
    demandScore: 99,
    growthRateYoY: 184,
    medianSalary: 178000,
    jobCount: 142000,
    momentum: 'Hyper-Growth',
    coOccurringSkills: ['LangChain', 'Python', 'Vector DB', 'Prompt Engineering', 'Azure AI Search'],
    description: 'Enterprise generative AI integration using Azure OpenAI models (GPT-4o), RAG pipelines, fine-tuning, and content safety.',
    azureEcosystemRelevance: 'Core enterprise GenAI service powering Azure Copilots, Semantic Search, and cognitive orchestration.'
  },
  {
    id: 'azure-ai-search',
    name: 'Azure AI Search (Vector / Hybrid)',
    category: 'AI & Machine Learning',
    demandScore: 95,
    growthRateYoY: 142,
    medianSalary: 168000,
    jobCount: 98500,
    momentum: 'Hyper-Growth',
    coOccurringSkills: ['Azure OpenAI', 'Embeddings', 'Semantic Kernel', 'Python', 'Cosmos DB'],
    description: 'Enterprise search engine supporting multi-modal vector search, semantic re-ranking, and large-scale knowledge retrieval for RAG.',
    azureEcosystemRelevance: 'The foundational vector retrieval engine for Azure GenAI and Copilot architectures.'
  },
  {
    id: 'kubernetes-aks',
    name: 'Azure Kubernetes Service (AKS)',
    category: 'DevOps & SRE',
    demandScore: 96,
    growthRateYoY: 38,
    medianSalary: 162000,
    jobCount: 215000,
    momentum: 'Strong Growth',
    coOccurringSkills: ['Docker', 'Terraform', 'Helm', 'ArgoCD', 'Prometheus', 'Azure DevOps'],
    description: 'Managed container orchestration on Azure, multi-cluster federation, service mesh (Istio), and GPU node pools for AI workloads.',
    azureEcosystemRelevance: 'Primary compute fabric for mission-critical microservices and distributed deep learning inferencing.'
  },
  {
    id: 'microsoft-fabric',
    name: 'Microsoft Fabric & Synapse',
    category: 'Data & Analytics',
    demandScore: 93,
    growthRateYoY: 126,
    medianSalary: 164000,
    jobCount: 88000,
    momentum: 'Hyper-Growth',
    coOccurringSkills: ['OneLake', 'PySpark', 'Delta Lake', 'Power BI', 'Data Factory', 'SQL'],
    description: 'Unified all-in-one analytics SaaS solution covering data engineering, data factory pipelines, real-time analytics, and governance.',
    azureEcosystemRelevance: 'The premier next-generation analytics architecture unifying Synapse, Data Factory, and Power BI.'
  },
  {
    id: 'terraform-bicep',
    name: 'Terraform & Azure Bicep (IaC)',
    category: 'Cloud & Azure',
    demandScore: 91,
    growthRateYoY: 29,
    medianSalary: 154000,
    jobCount: 176000,
    momentum: 'Strong Growth',
    coOccurringSkills: ['Azure DevOps', 'GitHub Actions', 'ARM Templates', 'Bash', 'Git'],
    description: 'Declarative Infrastructure as Code for automated provisioning, landing zones (CAF), and zero-trust cloud governance.',
    azureEcosystemRelevance: 'Industry standard for enterprise Azure Landing Zones and automated multi-environment deployments.'
  },
  {
    id: 'cosmos-db',
    name: 'Azure Cosmos DB & Vector Search',
    category: 'Data & Analytics',
    demandScore: 89,
    growthRateYoY: 48,
    medianSalary: 158000,
    jobCount: 112000,
    momentum: 'Strong Growth',
    coOccurringSkills: ['NoSQL', 'MongoDB API', 'PostgreSQL', 'Vector Indexing', 'Node.js', 'C#'],
    description: 'Globally distributed multi-model NoSQL database with single-digit millisecond latency, multi-region write, and integrated vector search.',
    azureEcosystemRelevance: 'Ultra-low latency transactional backend for real-time applications and conversational memory.'
  },
  {
    id: 'azure-sentinel-entra',
    name: 'Microsoft Sentinel & Entra ID',
    category: 'Cybersecurity',
    demandScore: 94,
    growthRateYoY: 54,
    medianSalary: 169000,
    jobCount: 135000,
    momentum: 'Hyper-Growth',
    coOccurringSkills: ['KQL', 'Zero Trust', 'Defender for Cloud', 'SOAR Playbooks', 'IAM'],
    description: 'Cloud-native SIEM/SOAR security analytics, automated threat hunting, and modern identity perimeter protection.',
    azureEcosystemRelevance: 'The backbone of Microsoft Cloud security operations and identity governance.'
  },
  {
    id: 'langchain-semantic-kernel',
    name: 'Semantic Kernel & LangChain',
    category: 'AI & Machine Learning',
    demandScore: 97,
    growthRateYoY: 210,
    medianSalary: 174000,
    jobCount: 128000,
    momentum: 'Hyper-Growth',
    coOccurringSkills: ['Azure OpenAI', 'Python', 'C#', 'Function Calling', 'RAG', 'Agentic Workflows'],
    description: 'Enterprise AI orchestration SDKs allowing developers to easily integrate AI models with conventional programming languages.',
    azureEcosystemRelevance: 'Microsoft open-source SDK natively designed for Azure OpenAI agents and enterprise copilot development.'
  },
  {
    id: 'azure-devops-gh-actions',
    name: 'Azure DevOps & GitHub Enterprise',
    category: 'DevOps & SRE',
    demandScore: 92,
    growthRateYoY: 26,
    medianSalary: 148000,
    jobCount: 195000,
    momentum: 'Strong Growth',
    coOccurringSkills: ['CI/CD Pipelines', 'Git', 'Docker', 'Kubernetes', 'SonarQube'],
    description: 'End-to-end continuous integration and deployment pipelines, artifact management, and automated release validation.',
    azureEcosystemRelevance: 'The standard development lifecycle platform for Microsoft cloud ecosystems.'
  },
  {
    id: 'python-pyspark',
    name: 'Python & PySpark',
    category: 'Data & Analytics',
    demandScore: 96,
    growthRateYoY: 34,
    medianSalary: 152000,
    jobCount: 310000,
    momentum: 'Strong Growth',
    coOccurringSkills: ['Pandas', 'NumPy', 'Azure Synapse', 'Databricks', 'SQL', 'Scikit-Learn'],
    description: 'Primary language for AI/ML modeling, distributed data processing, data science, and pipeline scripting.',
    azureEcosystemRelevance: 'Supported across Azure Machine Learning, Synapse Analytics, Fabric, and Azure Functions.'
  },
  {
    id: 'rust-systems',
    name: 'Rust & Systems Programming',
    category: 'Modern Web / Backend',
    demandScore: 88,
    growthRateYoY: 68,
    medianSalary: 172000,
    jobCount: 52000,
    momentum: 'Strong Growth',
    coOccurringSkills: ['WebAssembly', 'C++', 'Concurrency', 'Distributed Systems', 'Linux'],
    description: 'High-performance, memory-safe systems programming language experiencing rapid adoption in cloud infrastructure and high-throughput microservices.',
    azureEcosystemRelevance: 'Used heavily in hyper-scale cloud internals, WASM microservices, and high-performance serverless.'
  },
  {
    id: 'react-nextjs-ts',
    name: 'React, Next.js & TypeScript',
    category: 'Modern Web / Backend',
    demandScore: 90,
    growthRateYoY: 18,
    medianSalary: 142000,
    jobCount: 280000,
    momentum: 'Stable',
    coOccurringSkills: ['Node.js', 'TailwindCSS', 'GraphQL', 'REST APIs', 'Azure Static Web Apps'],
    description: 'Modern frontend ecosystem for enterprise web dashboards, server-side rendering, and responsive single-page applications.',
    azureEcosystemRelevance: 'Premier frontend stacks hosted on Azure Static Web Apps and Azure Container Apps.'
  },
  {
    id: 'dotnet-core-csharp',
    name: '.NET 8 / 9 & C# Enterprise',
    category: 'Modern Web / Backend',
    demandScore: 91,
    growthRateYoY: 22,
    medianSalary: 146000,
    jobCount: 260000,
    momentum: 'Stable',
    coOccurringSkills: ['ASP.NET Core', 'EF Core', 'Azure App Service', 'Microservices', 'SQL Server'],
    description: 'Cross-platform, blazing fast enterprise runtime for microservices, cloud APIs, and mission-critical backend systems.',
    azureEcosystemRelevance: 'First-class Microsoft runtime optimized specifically for Azure App Service, Functions, and Container Apps.'
  }
];

export const geoTalentHubs: GeoTalentHub[] = [
  {
    id: 'seattle',
    city: 'Seattle, WA',
    country: 'United States',
    region: 'North America',
    coordinates: { x: 18, y: 31 },
    totalTechListings: 184000,
    avgSalaryUsd: 188500,
    costOfLivingIndex: 88,
    purchasingPowerScore: 94,
    remoteFriendlyPercent: 42,
    yoyHiringGrowth: 16.2,
    topHiringSpecialties: ['Cloud Architecture', 'Generative AI', 'Systems Engineering', 'Distributed Storage'],
    topAzureSkills: ['Azure OpenAI', 'AKS', 'Fabric', 'Cosmos DB', 'Azure DevOps'],
    topCompanies: ['Microsoft', 'Amazon', 'Meta', 'Snowflake', 'F5 Networks', 'Tableau'],
    hiringVelocity: 'Very High'
  },
  {
    id: 'sf-bay-area',
    city: 'San Francisco Bay Area, CA',
    country: 'United States',
    region: 'North America',
    coordinates: { x: 16, y: 37 },
    totalTechListings: 245000,
    avgSalaryUsd: 208000,
    costOfLivingIndex: 100,
    purchasingPowerScore: 89,
    remoteFriendlyPercent: 46,
    yoyHiringGrowth: 18.5,
    topHiringSpecialties: ['LLM Ops / AI Research', 'Autonomous Agents', 'Staff Cloud Infrastructure', 'Security'],
    topAzureSkills: ['Azure OpenAI Studio', 'Semantic Kernel', 'Vector AI Search', 'AKS GPU Clusters'],
    topCompanies: ['OpenAI', 'Microsoft AI', 'Google', 'Anthropic', 'Apple', 'NVIDIA', 'Stripe'],
    hiringVelocity: 'Very High'
  },
  {
    id: 'austin',
    city: 'Austin, TX',
    country: 'United States',
    region: 'North America',
    coordinates: { x: 23, y: 44 },
    totalTechListings: 96000,
    avgSalaryUsd: 162000,
    costOfLivingIndex: 68,
    purchasingPowerScore: 96,
    remoteFriendlyPercent: 44,
    yoyHiringGrowth: 14.1,
    topHiringSpecialties: ['Fintech Engineering', 'Enterprise Cloud Migration', 'Data Analytics', 'DevOps'],
    topAzureSkills: ['Azure Synapse', 'Terraform', 'Azure App Service', 'Entra ID'],
    topCompanies: ['Dell Technologies', 'Tesla', 'Oracle', 'AMD', 'Indeed', 'Charles Schwab'],
    hiringVelocity: 'High'
  },
  {
    id: 'nyc',
    city: 'New York City, NY',
    country: 'United States',
    region: 'North America',
    coordinates: { x: 28, y: 34 },
    totalTechListings: 192000,
    avgSalaryUsd: 192000,
    costOfLivingIndex: 100,
    purchasingPowerScore: 84,
    remoteFriendlyPercent: 32,
    yoyHiringGrowth: 13.8,
    topHiringSpecialties: ['Quant & Financial AI', 'Cybersecurity & Compliance', 'Enterprise Data Platforms', 'Healthcare'],
    topAzureSkills: ['Microsoft Sentinel', 'Azure Confidential Computing', 'Synapse', 'Cosmos DB'],
    topCompanies: ['JPMorgan Chase', 'Morgan Stanley', 'Bloomberg', 'Microsoft NY', 'Datadog', 'Pfizer'],
    hiringVelocity: 'Very High'
  },
  {
    id: 'london',
    city: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    coordinates: { x: 48, y: 28 },
    totalTechListings: 142000,
    avgSalaryUsd: 132000,
    costOfLivingIndex: 82,
    purchasingPowerScore: 81,
    remoteFriendlyPercent: 40,
    yoyHiringGrowth: 12.4,
    topHiringSpecialties: ['Fintech Architecture', 'AI Safety & Governance', 'Cloud Modernization', 'Data Science'],
    topAzureSkills: ['Azure AI Search', 'Azure DevOps', 'Power BI / Fabric', 'Defender for Cloud'],
    topCompanies: ['DeepMind', 'Barclays', 'Revolut', 'Microsoft UK', 'HSBC', 'AstraZeneca'],
    hiringVelocity: 'High'
  },
  {
    id: 'bangalore',
    city: 'Bangalore (Bengaluru)',
    country: 'India',
    region: 'Asia Pacific',
    coordinates: { x: 71, y: 52 },
    totalTechListings: 275000,
    avgSalaryUsd: 48000,
    costOfLivingIndex: 26,
    purchasingPowerScore: 98,
    remoteFriendlyPercent: 38,
    yoyHiringGrowth: 24.8,
    topHiringSpecialties: ['Global R&D Centers', 'Full-Stack Cloud', 'Data Engineering', 'Azure Migration Specialists'],
    topAzureSkills: ['AKS', 'Azure Data Factory', 'Azure Bicep', 'Azure OpenAI', 'C# / .NET 8'],
    topCompanies: ['Microsoft India R&D', 'Infosys', 'TCS', 'Wipro', 'Target Tech', 'Walmart Global Tech', 'Flipkart'],
    hiringVelocity: 'Very High'
  },
  {
    id: 'berlin',
    city: 'Berlin',
    country: 'Germany',
    region: 'Europe',
    coordinates: { x: 52, y: 27 },
    totalTechListings: 74000,
    avgSalaryUsd: 108000,
    costOfLivingIndex: 65,
    purchasingPowerScore: 86,
    remoteFriendlyPercent: 48,
    yoyHiringGrowth: 11.9,
    topHiringSpecialties: ['CleanTech & Auto AI', 'Cloud Security & GDPR', 'Rust Microservices', 'DevOps'],
    topAzureSkills: ['Azure Sovereign Cloud', 'Terraform', 'Kubernetes', 'Microsoft Sentinel'],
    topCompanies: ['SAP', 'Delivery Hero', 'Zalando', 'BMW Tech', 'Siemens', 'N26'],
    hiringVelocity: 'Moderate'
  },
  {
    id: 'tokyo',
    city: 'Tokyo',
    country: 'Japan',
    region: 'Asia Pacific',
    coordinates: { x: 86, y: 38 },
    totalTechListings: 88000,
    avgSalaryUsd: 96000,
    costOfLivingIndex: 58,
    purchasingPowerScore: 88,
    remoteFriendlyPercent: 28,
    yoyHiringGrowth: 15.6,
    topHiringSpecialties: ['Digital Transformation (DX)', 'Robotics AI', 'Enterprise Cloud Infrastructure', 'Gaming'],
    topAzureSkills: ['Azure IoT Hub', 'Azure OpenAI (East Japan)', 'Synapse', 'Azure Arc'],
    topCompanies: ['Sony', 'Toyota Connected', 'Rakuten', 'NTT Data', 'SoftBank', 'Microsoft Japan'],
    hiringVelocity: 'High'
  },
  {
    id: 'toronto',
    city: 'Toronto, ON',
    country: 'Canada',
    region: 'North America',
    coordinates: { x: 26, y: 32 },
    totalTechListings: 82000,
    avgSalaryUsd: 124000,
    costOfLivingIndex: 72,
    purchasingPowerScore: 85,
    remoteFriendlyPercent: 45,
    yoyHiringGrowth: 13.5,
    topHiringSpecialties: ['AI Research & NLP', 'Banking Technology', 'Cloud Security', 'Healthcare Analytics'],
    topAzureSkills: ['Azure Machine Learning', 'AKS', 'Cosmos DB', 'Azure Monitor'],
    topCompanies: ['RBC Tech', 'Shopify', 'Vector Institute', 'Microsoft Canada', 'TD Bank'],
    hiringVelocity: 'High'
  },
  {
    id: 'singapore',
    city: 'Singapore',
    country: 'Singapore',
    region: 'Asia Pacific',
    coordinates: { x: 77, y: 58 },
    totalTechListings: 62000,
    avgSalaryUsd: 138000,
    costOfLivingIndex: 89,
    purchasingPowerScore: 87,
    remoteFriendlyPercent: 34,
    yoyHiringGrowth: 16.4,
    topHiringSpecialties: ['Fintech & Web3', 'APAC Cloud Infrastructure', 'AI Governance', 'Supply Chain Tech'],
    topAzureSkills: ['Azure OpenAI', 'Azure Arc', 'Synapse', 'ExpressRoute', 'Entra ID'],
    topCompanies: ['Grab', 'Sea Group', 'DBS Bank', 'Standard Chartered', 'Microsoft APAC', 'Shopee'],
    hiringVelocity: 'Very High'
  },
  {
    id: 'zurich',
    city: 'Zurich',
    country: 'Switzerland',
    region: 'Europe',
    coordinates: { x: 50, y: 31 },
    totalTechListings: 42000,
    avgSalaryUsd: 176000,
    costOfLivingIndex: 110,
    purchasingPowerScore: 92,
    remoteFriendlyPercent: 36,
    yoyHiringGrowth: 10.8,
    topHiringSpecialties: ['Fintech & Private Banking', 'Computer Vision & AI', 'High-Trust Cloud Architecture'],
    topAzureSkills: ['Azure Confidential Ledger', 'Azure OpenAI', 'AKS', 'Entra ID'],
    topCompanies: ['UBS', 'Credit Suisse', 'Google Zurich', 'Microsoft Switzerland', 'Roche', 'ABB'],
    hiringVelocity: 'Moderate'
  },
  {
    id: 'sydney',
    city: 'Sydney',
    country: 'Australia',
    region: 'Asia Pacific',
    coordinates: { x: 88, y: 78 },
    totalTechListings: 54000,
    avgSalaryUsd: 134000,
    costOfLivingIndex: 78,
    purchasingPowerScore: 86,
    remoteFriendlyPercent: 48,
    yoyHiringGrowth: 12.7,
    topHiringSpecialties: ['SaaS Scaling', 'Cloud Migration', 'Data Science & BI', 'DevSecOps'],
    topAzureSkills: ['Microsoft Fabric', 'Azure DevOps', 'Bicep', 'Azure Functions'],
    topCompanies: ['Atlassian', 'Canva', 'Commonwealth Bank', 'Macquarie Group', 'Microsoft ANZ'],
    hiringVelocity: 'High'
  }
];

export const azureCertProfiles: AzureCertProfile[] = [
  {
    code: 'AI-102',
    name: 'Azure AI Engineer Associate',
    level: 'Associate',
    iconColor: '#9333ea',
    medianSalaryBoostPercent: 28.5,
    avgAnnualSalary: 168000,
    activeJobOpenings: 42500,
    examDifficulty: 'Challenging',
    relatedRoles: ['AI Application Engineer', 'LLM Ops Specialist', 'Cognitive Solutions Architect'],
    topSkillTags: ['Azure OpenAI', 'Azure AI Search', 'Computer Vision', 'Speech Services', 'Document Intelligence'],
    summary: 'Validates ability to build, manage, and deploy AI solutions that leverage Azure OpenAI, Cognitive Services, and multi-modal knowledge retrieval.',
    recommendedLearningWeeks: 6
  },
  {
    code: 'AZ-305',
    name: 'Azure Solutions Architect Expert',
    level: 'Expert',
    iconColor: '#0078d4',
    medianSalaryBoostPercent: 32.0,
    avgAnnualSalary: 184000,
    activeJobOpenings: 68000,
    examDifficulty: 'Advanced',
    relatedRoles: ['Principal Cloud Architect', 'Enterprise Systems Architect', 'Chief Cloud Officer'],
    topSkillTags: ['Cloud Adoption Framework (CAF)', 'Well-Architected Framework', 'Multi-Region High Availability', 'Zero Trust', 'Governance'],
    summary: 'The gold standard for designing resilient, scalable, high-performance enterprise architectures across compute, storage, network, and security on Azure.',
    recommendedLearningWeeks: 10
  },
  {
    code: 'AZ-400',
    name: 'Azure DevOps Engineer Expert',
    level: 'Expert',
    iconColor: '#0ea5e9',
    medianSalaryBoostPercent: 24.5,
    avgAnnualSalary: 164000,
    activeJobOpenings: 56000,
    examDifficulty: 'Challenging',
    relatedRoles: ['Staff DevOps Engineer', 'Site Reliability Engineer (SRE)', 'Platform Engineer'],
    topSkillTags: ['Azure Pipelines', 'GitHub Actions', 'Terraform / Bicep', 'Continuous Compliance', 'ArgoCD / GitOps'],
    summary: 'Validates design and implementation of DevOps practices for version control, continuous integration, infrastructure as code, and automated security scans.',
    recommendedLearningWeeks: 8
  },
  {
    code: 'DP-203 / DP-600',
    name: 'Azure Data Engineer & Fabric Analytics',
    level: 'Associate',
    iconColor: '#10b981',
    medianSalaryBoostPercent: 26.0,
    avgAnnualSalary: 162000,
    activeJobOpenings: 61000,
    examDifficulty: 'Challenging',
    relatedRoles: ['Lead Data Engineer', 'Analytics Architect', 'Data Platform Specialist'],
    topSkillTags: ['Microsoft Fabric', 'Azure Synapse', 'OneLake', 'Azure Data Factory', 'PySpark', 'Delta Lake'],
    summary: 'Demonstrates expertise integrating, transforming, and consolidating data from structured and unstructured systems into enterprise analytics architectures.',
    recommendedLearningWeeks: 7
  },
  {
    code: 'SC-100',
    name: 'Cybersecurity Architect Expert',
    level: 'Expert',
    iconColor: '#ef4444',
    medianSalaryBoostPercent: 34.2,
    avgAnnualSalary: 189000,
    activeJobOpenings: 38000,
    examDifficulty: 'Advanced',
    relatedRoles: ['Chief Information Security Officer (CISO)', 'Lead Cloud Security Architect', 'SecOps Director'],
    topSkillTags: ['Zero Trust Architecture', 'Microsoft Sentinel', 'Defender for Cloud', 'Entra ID Privileged Identity', 'KQL'],
    summary: 'Designs holistic cybersecurity strategies and Zero Trust security architectures across hybrid and multi-cloud environments.',
    recommendedLearningWeeks: 9
  },
  {
    code: 'AZ-104',
    name: 'Azure Administrator Associate',
    level: 'Associate',
    iconColor: '#3b82f6',
    medianSalaryBoostPercent: 18.0,
    avgAnnualSalary: 136000,
    activeJobOpenings: 92000,
    examDifficulty: 'Moderate',
    relatedRoles: ['Azure Systems Administrator', 'Cloud Operations Engineer', 'Infrastructure Analyst'],
    topSkillTags: ['Virtual Networks', 'Azure RBAC', 'Storage Accounts', 'VM Scalesets', 'Azure Monitor'],
    summary: 'Foundational associate credential confirming hands-on ability to configure, manage, secure, and monitor compute, storage, and networking on Azure.',
    recommendedLearningWeeks: 5
  }
];

export const sampleJobPostings: JobPosting[] = [
  {
    id: 'job-az-001',
    title: 'Lead Azure GenAI & LLM Solutions Architect',
    company: 'Microsoft AI Cloud Ecosystems',
    companyTier: 'Big Tech',
    location: 'Redmond, WA (Hybrid / Remote Option)',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Hybrid',
    experienceLevel: 'Principal / Architect',
    salaryMin: 195000,
    salaryMax: 275000,
    salaryMedian: 235000,
    equityOffered: true,
    bonusPercent: 25,
    postedDate: '2 hours ago',
    skillsRequired: ['Azure OpenAI', 'Semantic Kernel', 'Python', 'Azure AI Search', 'LangChain', 'Prompt Flow', 'FastAPI'],
    azureServices: ['Azure OpenAI Service (GPT-4o)', 'Azure AI Search', 'Azure AI Studio', 'Cosmos DB', 'Azure Container Apps'],
    sector: 'AI & Deep Tech',
    description: 'Lead the architecture and design of enterprise generative AI platforms serving Fortune 100 customers. You will establish best practices for Retrieval-Augmented Generation (RAG), multi-modal LLM evaluation, fine-tuning workflows, and cognitive safety layers.',
    responsibilities: [
      'Architect enterprise-grade RAG solutions using Azure OpenAI, Azure AI Search vector hybrid index, and Semantic Kernel.',
      'Define governance frameworks for LLM evaluation, prompt orchestration, token rate limits, and Azure AI Content Safety.',
      'Collaborate with executive engineering teams to migrate legacy heuristic search systems to modern neural embeddings.',
      'Design high-throughput, low-latency microservices deployed on Azure Container Apps and AKS.'
    ],
    qualifications: [
      '8+ years in software architecture with 3+ years hands-on with LLMs and Vector Search systems.',
      'Deep expertise in Python, Semantic Kernel or LangChain, and Azure OpenAI APIs.',
      'Proven track record implementing production vector embeddings and hybrid re-ranking.'
    ],
    benefits: ['Full Health/Dental/Vision', 'Generous 401(k) Match (50% up to limit)', '$30,000+ Annual Equity Refreshers', 'Annual Learning & Azure Cert Stipend ($5,000)'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-az-002',
    title: 'Principal Cloud Platform & Kubernetes (AKS) Engineer',
    company: 'Fintech Velocity Global',
    companyTier: 'Enterprise 500',
    location: 'New York, NY / Remote',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Remote-First',
    experienceLevel: 'Principal / Architect',
    salaryMin: 180000,
    salaryMax: 245000,
    salaryMedian: 215000,
    equityOffered: true,
    bonusPercent: 20,
    postedDate: '5 hours ago',
    skillsRequired: ['Azure Kubernetes Service (AKS)', 'Terraform', 'Bicep', 'ArgoCD', 'Istio', 'Prometheus', 'Go'],
    azureServices: ['AKS', 'Azure Virtual Networks (VNet)', 'Azure Front Door', 'Azure Key Vault', 'Azure Monitor'],
    sector: 'Fintech & Quant',
    description: 'Build and maintain our global financial clearing mesh running across multi-region Azure Kubernetes clusters. Responsible for zero-downtime releases, sub-millisecond network latency optimization, and automated infrastructure as code.',
    responsibilities: [
      'Oversee infrastructure provisioning across 6 global Azure regions utilizing Terraform and Azure Bicep.',
      'Implement zero-trust network policies, mTLS with Istio service mesh, and Private Endpoints across all Azure services.',
      'Optimize AKS GPU node pools for real-time fraud detection and high-frequency risk modeling.',
      'Manage CI/CD pipelines via GitHub Actions and ArgoCD GitOps flows.'
    ],
    qualifications: [
      '7+ years experience managing production Kubernetes at enterprise scale.',
      'Expert level knowledge of Azure networking (ExpressRoute, VNets, NSGs, Private Link).',
      'AZ-305 or AZ-400 certification strongly preferred.'
    ],
    benefits: ['100% Remote Flexibility', 'Health & Wellness Stipend ($200/mo)', 'Discretionary Performance Bonus', 'Home Office Setup Grant ($2,500)'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-az-003',
    title: 'Senior Microsoft Fabric & Data Engineering Specialist',
    company: 'BioHealth Innovations',
    companyTier: 'High-Growth Unicorn',
    location: 'Boston, MA (Hybrid)',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Hybrid',
    experienceLevel: 'Senior',
    salaryMin: 155000,
    salaryMax: 195000,
    salaryMedian: 175000,
    equityOffered: true,
    bonusPercent: 15,
    postedDate: '1 day ago',
    skillsRequired: ['Microsoft Fabric', 'PySpark', 'Azure Synapse', 'OneLake', 'Delta Lake', 'SQL', 'Power BI'],
    azureServices: ['Microsoft Fabric', 'Azure Data Factory', 'Azure Data Lake Gen2', 'Synapse Analytics', 'Purview'],
    sector: 'HealthTech & Bio',
    description: 'Lead the transformation of genomic and clinical trial telemetry into real-time analytical insights using Microsoft Fabric and OneLake architectures.',
    responsibilities: [
      'Design and implement Medallion Lakehouse architectures (Bronze, Silver, Gold) on Microsoft Fabric OneLake.',
      'Develop robust PySpark pipelines processing petabyte-scale patient clinical observation streams.',
      'Ensure strict HIPAA and GDPR compliance using Microsoft Purview data governance.',
      'Create high-performance Direct Lake Power BI semantic models for medical researchers.'
    ],
    qualifications: [
      '5+ years building big data ETL pipelines with PySpark and SQL.',
      'Hands-on experience with Microsoft Fabric or Azure Synapse Analytics.',
      'DP-203 or DP-600 certified is a major plus.'
    ],
    benefits: ['Comprehensive Medical/Dental', 'Unlimited PTO', 'Equity Package', 'Parental Leave (16 weeks paid)'],
    visaSponsorship: false,
    workPermitRequired: true
  },
  {
    id: 'job-az-004',
    title: 'Staff Cloud Security & Zero Trust Architect',
    company: 'CyberShield Enterprise Defense',
    companyTier: 'Enterprise 500',
    location: 'London, UK / Remote',
    country: 'United Kingdom',
    region: 'Europe',
    remotePolicy: 'Remote-First',
    experienceLevel: 'Lead / Staff',
    salaryMin: 125000,
    salaryMax: 165000,
    salaryMedian: 145000,
    equityOffered: true,
    bonusPercent: 18,
    postedDate: '1 day ago',
    skillsRequired: ['Microsoft Sentinel', 'Defender for Cloud', 'Entra ID', 'KQL', 'Zero Trust', 'Incident Response'],
    azureServices: ['Microsoft Sentinel', 'Microsoft Entra ID P2', 'Microsoft Defender for Cloud', 'Azure Key Vault', 'Azure Policy'],
    sector: 'Cybersecurity',
    description: 'Architect and execute defense-in-depth strategies across hybrid enterprise clouds using Microsoft Sentinel SIEM/SOAR, automated KQL threat hunting, and modern identity governance.',
    responsibilities: [
      'Build automated incident response playbooks using Azure Logic Apps and Microsoft Sentinel SOAR.',
      'Audit cloud workloads against CIS Benchmarks, NIST CSF, and ISO 27001 using Microsoft Defender for Cloud.',
      'Implement Conditional Access and Privileged Identity Management (PIM) through Microsoft Entra ID.',
      'Write complex KQL queries to detect APTs and insider threats across hundreds of log sources.'
    ],
    qualifications: [
      '6+ years in cloud cybersecurity architecture and incident response.',
      'Expert proficiency with KQL (Kusto Query Language) and SIEM analytics.',
      'SC-100 or AZ-500 certification required.'
    ],
    benefits: ['Pension Scheme (8% match)', 'Flexible Work Model', 'Annual Security Conference Budget', 'Health Insurance'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-az-005',
    title: 'Senior Full-Stack Azure & .NET Core Engineer',
    company: 'OmniCommerce Cloud',
    companyTier: 'High-Growth Unicorn',
    location: 'Austin, TX / Remote',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Remote-First',
    experienceLevel: 'Senior',
    salaryMin: 140000,
    salaryMax: 180000,
    salaryMedian: 160000,
    equityOffered: true,
    bonusPercent: 12,
    postedDate: '3 days ago',
    skillsRequired: ['.NET 8', 'C#', 'React', 'TypeScript', 'Azure Cosmos DB', 'Azure Functions', 'REST APIs'],
    azureServices: ['Azure App Service', 'Azure Functions', 'Azure Cosmos DB', 'Azure Service Bus', 'Azure Redis Cache'],
    sector: 'E-commerce & Retail',
    description: 'Build high-scale checkout, inventory reservation, and real-time storefront systems powering over $4B in annual gross merchandise volume.',
    responsibilities: [
      'Develop asynchronous microservices in .NET 8 / C# with event-driven architecture over Azure Service Bus.',
      'Construct reactive customer dashboards and real-time inventory management in React 18 & TypeScript.',
      'Optimize Azure Cosmos DB queries and partitioning strategies to sustain 50,000+ peak requests per second.',
      'Maintain automated testing suites and CI/CD deployment pipelines.'
    ],
    qualifications: [
      '5+ years building web applications with C# / .NET and modern React.',
      'Deep understanding of distributed systems, caching, and eventual consistency.',
      'Experience with Azure cloud-native PaaS services.'
    ],
    benefits: ['401(k) with 4% match', 'Flexible Working Hours', 'Comprehensive Healthcare', 'Stock Options'],
    visaSponsorship: false,
    workPermitRequired: true
  },
  {
    id: 'job-az-006',
    title: 'Azure Cloud MLOps & Autonomous Pipeline Engineer',
    company: 'NeuralDrive Technologies',
    companyTier: 'High-Growth Unicorn',
    location: 'San Francisco, CA (On-Site / Hybrid)',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Hybrid',
    experienceLevel: 'Senior',
    salaryMin: 175000,
    salaryMax: 230000,
    salaryMedian: 202000,
    equityOffered: true,
    bonusPercent: 20,
    postedDate: '4 days ago',
    skillsRequired: ['Azure Machine Learning', 'PyTorch', 'MLflow', 'Docker', 'Kubernetes', 'Python', 'NVIDIA Triton'],
    azureServices: ['Azure Machine Learning', 'AKS GPU Clusters', 'Azure Blob Storage', 'Azure Event Hubs'],
    sector: 'Autonomous & Robotics',
    description: 'Build automated continuous training and inference pipelines for computer vision models running in autonomous vehicle simulations and edge fleets.',
    responsibilities: [
      'Automate model lifecycle tracking, hyperparameter optimization, and registry using Azure Machine Learning & MLflow.',
      'Deploy low-latency inferencing endpoints on AKS equipped with NVIDIA A100 / H100 GPU clusters.',
      'Build automated data labeling and synthetic data ingestion pipelines from Azure Event Hubs into Data Lake Gen2.',
      'Establish continuous model drift monitoring and automated retraining triggers.'
    ],
    qualifications: [
      '4+ years in MLOps or Production ML Engineering.',
      'Strong proficiency in Python, PyTorch, Docker, and distributed GPU compute.',
      'Hands-on experience with Azure ML SDK v2.'
    ],
    benefits: ['Top-tier Equity Grant', 'Free Gourmet Lunch & Dinner', 'Full Healthcare & Mental Wellness', 'Commuter Benefits'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-az-007',
    title: 'Lead Azure Cloud Migration Consultant',
    company: 'Enterprise Global Advisory',
    companyTier: 'Enterprise 500',
    location: 'Bangalore, India (Hybrid)',
    country: 'India',
    region: 'Asia Pacific',
    remotePolicy: 'Hybrid',
    experienceLevel: 'Lead / Staff',
    salaryMin: 45000,
    salaryMax: 65000,
    salaryMedian: 55000,
    equityOffered: false,
    bonusPercent: 15,
    postedDate: '5 days ago',
    skillsRequired: ['Azure Migrate', 'Azure Bicep', 'VMware Migration', 'SQL Server Migration', 'Enterprise Networking'],
    azureServices: ['Azure Migrate', 'Azure Virtual WAN', 'Azure SQL Managed Instance', 'Azure Arc', 'Azure Site Recovery'],
    sector: 'Cloud & Enterprise SaaS',
    description: 'Guide multi-national enterprise clients through datacenter evacuation and seamless migration to Microsoft Azure hybrid cloud architectures.',
    responsibilities: [
      'Perform detailed workload assessments and TCO analysis using Azure Migrate.',
      'Architect target landing zones adhering to the Microsoft Cloud Adoption Framework (CAF).',
      'Execute zero-data-loss database migrations from on-premise SQL Server / Oracle to Azure SQL Managed Instance.',
      'Conduct knowledge transfer workshops for client engineering teams.'
    ],
    qualifications: [
      '8+ years in IT infrastructure and enterprise cloud migrations.',
      'AZ-305 and AZ-104 certifications are mandatory.',
      'Extensive experience with hybrid networking, ExpressRoute, and Azure Arc.'
    ],
    benefits: ['Annual Performance Bonus', 'Medical Insurance for Family', 'Certification Re-imbursement', 'Company Transport'],
    visaSponsorship: false,
    workPermitRequired: false
  },
  {
    id: 'job-az-008',
    title: 'Azure IoT & Edge Solutions Architect',
    company: 'SmartGrid Power Systems',
    companyTier: 'Enterprise 500',
    location: 'Berlin, Germany / Remote',
    country: 'Germany',
    region: 'Europe',
    remotePolicy: 'Remote-First',
    experienceLevel: 'Senior',
    salaryMin: 105000,
    salaryMax: 135000,
    salaryMedian: 120000,
    equityOffered: true,
    bonusPercent: 10,
    postedDate: '6 days ago',
    skillsRequired: ['Azure IoT Hub', 'Azure IoT Edge', 'Rust / C++', 'MQTT', 'Stream Analytics', 'Time Series Insights'],
    azureServices: ['Azure IoT Hub', 'Azure IoT Edge', 'Azure Stream Analytics', 'Azure Data Explorer (ADX)', 'Cosmos DB'],
    sector: 'Cloud & Enterprise SaaS',
    description: 'Connect millions of industrial wind turbines, smart meters, and solar grids to Microsoft Azure real-time telemetry processing pipelines.',
    responsibilities: [
      'Architect resilient edge computing runtimes using Azure IoT Edge and containerized Rust modules.',
      'Stream and analyze 200,000+ telemetry events per second via Azure Stream Analytics and Azure Data Explorer.',
      'Implement bi-directional device command and control with Azure IoT Hub device twins and DPS.',
      'Ensure compliance with European energy regulations and industrial cybersecurity standards.'
    ],
    qualifications: [
      '5+ years architecting IoT or industrial telemetry solutions.',
      'Proficiency with C++, Rust, or C# for edge development.',
      'Deep understanding of MQTT, OPC-UA, and AMQP protocols.'
    ],
    benefits: ['30 Days Paid Vacation', 'Public Transport Pass', 'Flexible Remote Policy', 'Educational Budget'],
    visaSponsorship: true,
    workPermitRequired: false
  }
];

export const skillRelationshipNodes = [
  { id: 'azure-openai', label: 'Azure OpenAI', category: 'AI', x: 280, y: 180, radius: 28, color: '#9333ea', demand: 99 },
  { id: 'semantic-kernel', label: 'Semantic Kernel', category: 'AI', x: 380, y: 120, radius: 22, color: '#a855f7', demand: 97 },
  { id: 'azure-ai-search', label: 'Azure AI Search', category: 'AI', x: 220, y: 280, radius: 24, color: '#3b82f6', demand: 95 },
  { id: 'python', label: 'Python', category: 'Language', x: 420, y: 250, radius: 26, color: '#eab308', demand: 98 },
  { id: 'aks', label: 'Azure Kubernetes (AKS)', category: 'DevOps', x: 160, y: 400, radius: 28, color: '#0284c7', demand: 96 },
  { id: 'terraform', label: 'Terraform & IaC', category: 'DevOps', x: 260, y: 460, radius: 24, color: '#6366f1', demand: 91 },
  { id: 'azure-bicep', label: 'Azure Bicep', category: 'DevOps', x: 120, y: 520, radius: 20, color: '#0ea5e9', demand: 86 },
  { id: 'microsoft-fabric', label: 'Microsoft Fabric', category: 'Data', x: 540, y: 340, radius: 26, color: '#10b981', demand: 93 },
  { id: 'synapse', label: 'Azure Synapse', category: 'Data', x: 620, y: 260, radius: 22, color: '#059669', demand: 89 },
  { id: 'pyspark', label: 'PySpark / Delta', category: 'Data', x: 520, y: 440, radius: 22, color: '#f59e0b', demand: 94 },
  { id: 'cosmos-db', label: 'Cosmos DB', category: 'Data', x: 360, y: 360, radius: 24, color: '#06b6d4', demand: 89 },
  { id: 'sentinel', label: 'Microsoft Sentinel', category: 'Security', x: 680, y: 150, radius: 24, color: '#ef4444', demand: 94 },
  { id: 'entra-id', label: 'Entra ID (Zero Trust)', category: 'Security', x: 740, y: 240, radius: 22, color: '#dc2626', demand: 92 },
  { id: 'kql', label: 'KQL Analytics', category: 'Security', x: 780, y: 130, radius: 18, color: '#f43f5e', demand: 88 },
  { id: 'dotnet-csharp', label: '.NET 8 / C#', category: 'Backend', x: 440, y: 480, radius: 24, color: '#8b5cf6', demand: 91 },
  { id: 'react-ts', label: 'React & TypeScript', category: 'Frontend', x: 320, y: 560, radius: 22, color: '#38bdf8', demand: 90 }
];

export const skillRelationshipEdges = [
  { source: 'azure-openai', target: 'semantic-kernel', weight: 0.95 },
  { source: 'azure-openai', target: 'azure-ai-search', weight: 0.92 },
  { source: 'azure-openai', target: 'python', weight: 0.88 },
  { source: 'azure-openai', target: 'cosmos-db', weight: 0.74 },
  { source: 'azure-ai-search', target: 'cosmos-db', weight: 0.82 },
  { source: 'semantic-kernel', target: 'dotnet-csharp', weight: 0.86 },
  { source: 'aks', target: 'terraform', weight: 0.90 },
  { source: 'aks', target: 'azure-bicep', weight: 0.82 },
  { source: 'terraform', target: 'azure-bicep', weight: 0.76 },
  { source: 'microsoft-fabric', target: 'synapse', weight: 0.94 },
  { source: 'microsoft-fabric', target: 'pyspark', weight: 0.91 },
  { source: 'synapse', target: 'pyspark', weight: 0.89 },
  { source: 'pyspark', target: 'python', weight: 0.92 },
  { source: 'sentinel', target: 'entra-id', weight: 0.96 },
  { source: 'sentinel', target: 'kql', weight: 0.98 },
  { source: 'entra-id', target: 'aks', weight: 0.72 },
  { source: 'dotnet-csharp', target: 'cosmos-db', weight: 0.85 },
  { source: 'dotnet-csharp', target: 'react-ts', weight: 0.78 }
];
