import {
  JobPosting,
  SkillTrend,
  GeoTalentHub,
  AzureCertProfile,
  HistoricalTrendPoint,
  MacroMarketStats
} from '../types/market';

export const macroStats: MacroMarketStats = {
  totalActiveJobs: 2481920,
  yoyHiringGrowth: 14.8,
  avgTechSalary: 146800,
  remotePercent: 38.4,
  hybridPercent: 44.2,
  onsitePercent: 17.4,
  avgTimeToFillDays: 34,
  totalCompaniesHiring: 68420,
  azureSkillMarketShare: 41.2, // % of enterprise cloud listings mentioning Azure stacks
  lastUpdated: 'Live Continuous Ingestion (Azure Event Hubs)'
};

export const historicalTrends: HistoricalTrendPoint[] = [
  { yearQuarter: '2022 Q1', aiMlDemand: 45, cloudDevOpsDemand: 78, cybersecurityDemand: 58, dataEngineeringDemand: 62, fullstackDemand: 88, layoffsIndex: 12, medianTechSalary: 128000 },
  { yearQuarter: '2022 Q2', aiMlDemand: 48, cloudDevOpsDemand: 82, cybersecurityDemand: 60, dataEngineeringDemand: 65, fullstackDemand: 90, layoffsIndex: 25, medianTechSalary: 131000 },
  { yearQuarter: '2022 Q3', aiMlDemand: 52, cloudDevOpsDemand: 84, cybersecurityDemand: 63, dataEngineeringDemand: 68, fullstackDemand: 86, layoffsIndex: 48, medianTechSalary: 132500 },
  { yearQuarter: '2022 Q4', aiMlDemand: 58, cloudDevOpsDemand: 80, cybersecurityDemand: 65, dataEngineeringDemand: 67, fullstackDemand: 78, layoffsIndex: 85, medianTechSalary: 130000 },
  { yearQuarter: '2023 Q1', aiMlDemand: 69, cloudDevOpsDemand: 79, cybersecurityDemand: 68, dataEngineeringDemand: 70, fullstackDemand: 72, layoffsIndex: 110, medianTechSalary: 132000 },
  { yearQuarter: '2023 Q2', aiMlDemand: 78, cloudDevOpsDemand: 83, cybersecurityDemand: 71, dataEngineeringDemand: 73, fullstackDemand: 74, layoffsIndex: 75, medianTechSalary: 135000 },
  { yearQuarter: '2023 Q3', aiMlDemand: 84, cloudDevOpsDemand: 86, cybersecurityDemand: 74, dataEngineeringDemand: 76, fullstackDemand: 77, layoffsIndex: 52, medianTechSalary: 137500 },
  { yearQuarter: '2023 Q4', aiMlDemand: 89, cloudDevOpsDemand: 88, cybersecurityDemand: 77, dataEngineeringDemand: 80, fullstackDemand: 80, layoffsIndex: 42, medianTechSalary: 139000 },
  { yearQuarter: '2024 Q1', aiMlDemand: 94, cloudDevOpsDemand: 90, cybersecurityDemand: 81, dataEngineeringDemand: 84, fullstackDemand: 82, layoffsIndex: 38, medianTechSalary: 141000 },
  { yearQuarter: '2024 Q2', aiMlDemand: 98, cloudDevOpsDemand: 92, cybersecurityDemand: 84, dataEngineeringDemand: 87, fullstackDemand: 84, layoffsIndex: 28, medianTechSalary: 143000 },
  { yearQuarter: '2024 Q3', aiMlDemand: 104, cloudDevOpsDemand: 94, cybersecurityDemand: 86, dataEngineeringDemand: 89, fullstackDemand: 85, layoffsIndex: 22, medianTechSalary: 144500 },
  { yearQuarter: '2024 Q4', aiMlDemand: 112, cloudDevOpsDemand: 96, cybersecurityDemand: 89, dataEngineeringDemand: 92, fullstackDemand: 87, layoffsIndex: 18, medianTechSalary: 146000 },
  { yearQuarter: '2025 Q1', aiMlDemand: 124, cloudDevOpsDemand: 99, cybersecurityDemand: 92, dataEngineeringDemand: 95, fullstackDemand: 89, layoffsIndex: 14, medianTechSalary: 148500 },
  { yearQuarter: '2025 Q2', aiMlDemand: 138, cloudDevOpsDemand: 103, cybersecurityDemand: 95, dataEngineeringDemand: 98, fullstackDemand: 91, layoffsIndex: 12, medianTechSalary: 151000 },
  { yearQuarter: '2025 Q3', aiMlDemand: 152, cloudDevOpsDemand: 107, cybersecurityDemand: 98, dataEngineeringDemand: 102, fullstackDemand: 93, layoffsIndex: 11, medianTechSalary: 153500 },
  { yearQuarter: '2025 Q4', aiMlDemand: 165, cloudDevOpsDemand: 112, cybersecurityDemand: 101, dataEngineeringDemand: 105, fullstackDemand: 95, layoffsIndex: 10, medianTechSalary: 156000 },
  { yearQuarter: '2026 Q1', aiMlDemand: 178, cloudDevOpsDemand: 118, cybersecurityDemand: 105, dataEngineeringDemand: 109, fullstackDemand: 97, layoffsIndex: 9, medianTechSalary: 159000 },
  { yearQuarter: '2026 Q2 (Est)', aiMlDemand: 192, cloudDevOpsDemand: 124, cybersecurityDemand: 109, dataEngineeringDemand: 114, fullstackDemand: 99, layoffsIndex: 8, medianTechSalary: 162000 },
  { yearQuarter: '2026 Q3 (Est)', aiMlDemand: 208, cloudDevOpsDemand: 130, cybersecurityDemand: 113, dataEngineeringDemand: 118, fullstackDemand: 102, layoffsIndex: 8, medianTechSalary: 165000 }
];

export const skillTrendsData: SkillTrend[] = [
  {
    id: 'azure-openai',
    name: 'Azure OpenAI & AI Studio',
    category: 'AI & Machine Learning',
    demandScore: 99,
    growthRateYoY: 184,
    medianSalary: 178000,
    jobCount: 142000,
    momentum: 'Hyper-Growth',
    coOccurringSkills: ['LangChain', 'Python', 'Vector DB', 'Prompt Engineering', 'Azure AI Search'],
    description: 'Enterprise generative AI integration using Azure OpenAI models (GPT-4o), RAG pipelines, fine-tuning, and content safety.',
    azureEcosystemRelevance: 'Core enterprise GenAI service powering Azure Copilots, Semantic Search, and cognitive orchestration.'
  },
  {
    id: 'azure-ai-search',
    name: 'Azure AI Search (Vector / Hybrid)',
    category: 'AI & Machine Learning',
    demandScore: 95,
    growthRateYoY: 142,
    medianSalary: 168000,
    jobCount: 98500,
    momentum: 'Hyper-Growth',
    coOccurringSkills: ['Azure OpenAI', 'Embeddings', 'Semantic Kernel', 'Python', 'Cosmos DB'],
    description: 'Enterprise search engine supporting multi-modal vector search, semantic re-ranking, and large-scale knowledge retrieval for RAG.',
    azureEcosystemRelevance: 'The foundational vector retrieval engine for Azure GenAI and Copilot architectures.'
  },
  {
    id: 'kubernetes-aks',
    name: 'Azure Kubernetes Service (AKS)',
    category: 'DevOps & SRE',
    demandScore: 96,
    growthRateYoY: 38,
    medianSalary: 162000,
    jobCount: 215000,
    momentum: 'Strong Growth',
    coOccurringSkills: ['Docker', 'Terraform', 'Helm', 'ArgoCD', 'Prometheus', 'Azure DevOps'],
    description: 'Managed container orchestration on Azure, multi-cluster federation, service mesh (Istio), and GPU node pools for AI workloads.',
    azureEcosystemRelevance: 'Primary compute fabric for mission-critical microservices and distributed deep learning inferencing.'
  },
  {
    id: 'microsoft-fabric',
    name: 'Microsoft Fabric & Synapse',
    category: 'Data & Analytics',
    demandScore: 93,
    growthRateYoY: 126,
    medianSalary: 164000,
    jobCount: 88000,
    momentum: 'Hyper-Growth',
    coOccurringSkills: ['OneLake', 'PySpark', 'Delta Lake', 'Power BI', 'Data Factory', 'SQL'],
    description: 'Unified all-in-one analytics SaaS solution covering data engineering, data factory pipelines, real-time analytics, and governance.',
    azureEcosystemRelevance: 'The premier next-generation analytics architecture unifying Synapse, Data Factory, and Power BI.'
  },
  {
    id: 'terraform-bicep',
    name: 'Terraform & Azure Bicep (IaC)',
    category: 'Cloud & Azure',
    demandScore: 91,
    growthRateYoY: 29,
    medianSalary: 154000,
    jobCount: 176000,
    momentum: 'Strong Growth',
    coOccurringSkills: ['Azure DevOps', 'GitHub Actions', 'ARM Templates', 'Bash', 'Git'],
    description: 'Declarative Infrastructure as Code for automated provisioning, landing zones (CAF), and zero-trust cloud governance.',
    azureEcosystemRelevance: 'Industry standard for enterprise Azure Landing Zones and automated multi-environment deployments.'
  },
  {
    id: 'cosmos-db',
    name: 'Azure Cosmos DB & Vector Search',
    category: 'Data & Analytics',
    demandScore: 89,
    growthRateYoY: 48,
    medianSalary: 158000,
    jobCount: 112000,
    momentum: 'Strong Growth',
    coOccurringSkills: ['NoSQL', 'MongoDB API', 'PostgreSQL', 'Vector Indexing', 'Node.js', 'C#'],
    description: 'Globally distributed multi-model NoSQL database with single-digit millisecond latency, multi-region write, and integrated vector search.',
    azureEcosystemRelevance: 'Ultra-low latency transactional backend for real-time applications and conversational memory.'
  },
  {
    id: 'azure-sentinel-entra',
    name: 'Microsoft Sentinel & Entra ID',
    category: 'Cybersecurity',
    demandScore: 94,
    growthRateYoY: 54,
    medianSalary: 169000,
    jobCount: 135000,
    momentum: 'Hyper-Growth',
    coOccurringSkills: ['KQL', 'Zero Trust', 'Defender for Cloud', 'SOAR Playbooks', 'IAM'],
    description: 'Cloud-native SIEM/SOAR security analytics, automated threat hunting, and modern identity perimeter protection.',
    azureEcosystemRelevance: 'The backbone of Microsoft Cloud security operations and identity governance.'
  },
  {
    id: 'langchain-semantic-kernel',
    name: 'Semantic Kernel & LangChain',
    category: 'AI & Machine Learning',
    demandScore: 97,
    growthRateYoY: 210,
    medianSalary: 174000,
    jobCount: 128000,
    momentum: 'Hyper-Growth',
    coOccurringSkills: ['Azure OpenAI', 'Python', 'C#', 'Function Calling', 'RAG', 'Agentic Workflows'],
    description: 'Enterprise AI orchestration SDKs allowing developers to easily integrate AI models with conventional programming languages.',
    azureEcosystemRelevance: 'Microsoft open-source SDK natively designed for Azure OpenAI agents and enterprise copilot development.'
  },
  {
    id: 'azure-devops-gh-actions',
    name: 'Azure DevOps & GitHub Enterprise',
    category: 'DevOps & SRE',
    demandScore: 92,
    growthRateYoY: 26,
    medianSalary: 148000,
    jobCount: 195000,
    momentum: 'Strong Growth',
    coOccurringSkills: ['CI/CD Pipelines', 'Git', 'Docker', 'Kubernetes', 'SonarQube'],
    description: 'End-to-end continuous integration and deployment pipelines, artifact management, and automated release validation.',
    azureEcosystemRelevance: 'The standard development lifecycle platform for Microsoft cloud ecosystems.'
  },
  {
    id: 'python-pyspark',
    name: 'Python & PySpark',
    category: 'Data & Analytics',
    demandScore: 96,
    growthRateYoY: 34,
    medianSalary: 152000,
    jobCount: 310000,
    momentum: 'Strong Growth',
    coOccurringSkills: ['Pandas', 'NumPy', 'Azure Synapse', 'Databricks', 'SQL', 'Scikit-Learn'],
    description: 'Primary language for AI/ML modeling, distributed data processing, data science, and pipeline scripting.',
    azureEcosystemRelevance: 'Supported across Azure Machine Learning, Synapse Analytics, Fabric, and Azure Functions.'
  },
  {
    id: 'rust-systems',
    name: 'Rust & Systems Programming',
    category: 'Modern Web / Backend',
    demandScore: 88,
    growthRateYoY: 68,
    medianSalary: 172000,
    jobCount: 52000,
    momentum: 'Strong Growth',
    coOccurringSkills: ['WebAssembly', 'C++', 'Concurrency', 'Distributed Systems', 'Linux'],
    description: 'High-performance, memory-safe systems programming language experiencing rapid adoption in cloud infrastructure and high-throughput microservices.',
    azureEcosystemRelevance: 'Used heavily in hyper-scale cloud internals, WASM microservices, and high-performance serverless.'
  },
  {
    id: 'react-nextjs-ts',
    name: 'React, Next.js & TypeScript',
    category: 'Modern Web / Backend',
    demandScore: 90,
    growthRateYoY: 18,
    medianSalary: 142000,
    jobCount: 280000,
    momentum: 'Stable',
    coOccurringSkills: ['Node.js', 'TailwindCSS', 'GraphQL', 'REST APIs', 'Azure Static Web Apps'],
    description: 'Modern frontend ecosystem for enterprise web dashboards, server-side rendering, and responsive single-page applications.',
    azureEcosystemRelevance: 'Premier frontend stacks hosted on Azure Static Web Apps and Azure Container Apps.'
  },
  {
    id: 'dotnet-core-csharp',
    name: '.NET 8 / 9 & C# Enterprise',
    category: 'Modern Web / Backend',
    demandScore: 91,
    growthRateYoY: 22,
    medianSalary: 146000,
    jobCount: 260000,
    momentum: 'Stable',
    coOccurringSkills: ['ASP.NET Core', 'EF Core', 'Azure App Service', 'Microservices', 'SQL Server'],
    description: 'Cross-platform, blazing fast enterprise runtime for microservices, cloud APIs, and mission-critical backend systems.',
    azureEcosystemRelevance: 'First-class Microsoft runtime optimized specifically for Azure App Service, Functions, and Container Apps.'
  }
];

export const geoTalentHubs: GeoTalentHub[] = [
  {
    id: 'seattle',
    city: 'Seattle, WA',
    country: 'United States',
    region: 'North America',
    coordinates: { x: 18, y: 31 },
    totalTechListings: 184000,
    avgSalaryUsd: 188500,
    costOfLivingIndex: 88,
    purchasingPowerScore: 94,
    remoteFriendlyPercent: 42,
    yoyHiringGrowth: 16.2,
    topHiringSpecialties: ['Cloud Architecture', 'Generative AI', 'Systems Engineering', 'Distributed Storage'],
    topAzureSkills: ['Azure OpenAI', 'AKS', 'Fabric', 'Cosmos DB', 'Azure DevOps'],
    topCompanies: ['Microsoft', 'Amazon', 'Meta', 'Snowflake', 'F5 Networks', 'Tableau'],
    hiringVelocity: 'Very High'
  },
  {
    id: 'sf-bay-area',
    city: 'San Francisco Bay Area, CA',
    country: 'United States',
    region: 'North America',
    coordinates: { x: 16, y: 37 },
    totalTechListings: 245000,
    avgSalaryUsd: 208000,
    costOfLivingIndex: 100,
    purchasingPowerScore: 89,
    remoteFriendlyPercent: 46,
    yoyHiringGrowth: 18.5,
    topHiringSpecialties: ['LLM Ops / AI Research', 'Autonomous Agents', 'Staff Cloud Infrastructure', 'Security'],
    topAzureSkills: ['Azure OpenAI Studio', 'Semantic Kernel', 'Vector AI Search', 'AKS GPU Clusters'],
    topCompanies: ['OpenAI', 'Microsoft AI', 'Google', 'Anthropic', 'Apple', 'NVIDIA', 'Stripe'],
    hiringVelocity: 'Very High'
  },
  {
    id: 'austin',
    city: 'Austin, TX',
    country: 'United States',
    region: 'North America',
    coordinates: { x: 23, y: 44 },
    totalTechListings: 96000,
    avgSalaryUsd: 162000,
    costOfLivingIndex: 68,
    purchasingPowerScore: 96,
    remoteFriendlyPercent: 44,
    yoyHiringGrowth: 14.1,
    topHiringSpecialties: ['Fintech Engineering', 'Enterprise Cloud Migration', 'Data Analytics', 'DevOps'],
    topAzureSkills: ['Azure Synapse', 'Terraform', 'Azure App Service', 'Entra ID'],
    topCompanies: ['Dell Technologies', 'Tesla', 'Oracle', 'AMD', 'Indeed', 'Charles Schwab'],
    hiringVelocity: 'High'
  },
  {
    id: 'nyc',
    city: 'New York City, NY',
    country: 'United States',
    region: 'North America',
    coordinates: { x: 28, y: 34 },
    totalTechListings: 192000,
    avgSalaryUsd: 192000,
    costOfLivingIndex: 100,
    purchasingPowerScore: 84,
    remoteFriendlyPercent: 32,
    yoyHiringGrowth: 13.8,
    topHiringSpecialties: ['Quant & Financial AI', 'Cybersecurity & Compliance', 'Enterprise Data Platforms', 'Healthcare'],
    topAzureSkills: ['Microsoft Sentinel', 'Azure Confidential Computing', 'Synapse', 'Cosmos DB'],
    topCompanies: ['JPMorgan Chase', 'Morgan Stanley', 'Bloomberg', 'Microsoft NY', 'Datadog', 'Pfizer'],
    hiringVelocity: 'Very High'
  },
  {
    id: 'london',
    city: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    coordinates: { x: 48, y: 28 },
    totalTechListings: 142000,
    avgSalaryUsd: 132000,
    costOfLivingIndex: 82,
    purchasingPowerScore: 81,
    remoteFriendlyPercent: 40,
    yoyHiringGrowth: 12.4,
    topHiringSpecialties: ['Fintech Architecture', 'AI Safety & Governance', 'Cloud Modernization', 'Data Science'],
    topAzureSkills: ['Azure AI Search', 'Azure DevOps', 'Power BI / Fabric', 'Defender for Cloud'],
    topCompanies: ['DeepMind', 'Barclays', 'Revolut', 'Microsoft UK', 'HSBC', 'AstraZeneca'],
    hiringVelocity: 'High'
  },
  {
    id: 'bangalore',
    city: 'Bangalore (Bengaluru)',
    country: 'India',
    region: 'Asia Pacific',
    coordinates: { x: 71, y: 52 },
    totalTechListings: 275000,
    avgSalaryUsd: 48000,
    costOfLivingIndex: 26,
    purchasingPowerScore: 98,
    remoteFriendlyPercent: 38,
    yoyHiringGrowth: 24.8,
    topHiringSpecialties: ['Global R&D Centers', 'Full-Stack Cloud', 'Data Engineering', 'Azure Migration Specialists'],
    topAzureSkills: ['AKS', 'Azure Data Factory', 'Azure Bicep', 'Azure OpenAI', 'C# / .NET 8'],
    topCompanies: ['Microsoft India R&D', 'Infosys', 'TCS', 'Wipro', 'Target Tech', 'Walmart Global Tech', 'Flipkart'],
    hiringVelocity: 'Very High'
  },
  {
    id: 'berlin',
    city: 'Berlin',
    country: 'Germany',
    region: 'Europe',
    coordinates: { x: 52, y: 27 },
    totalTechListings: 74000,
    avgSalaryUsd: 108000,
    costOfLivingIndex: 65,
    purchasingPowerScore: 86,
    remoteFriendlyPercent: 48,
    yoyHiringGrowth: 11.9,
    topHiringSpecialties: ['CleanTech & Auto AI', 'Cloud Security & GDPR', 'Rust Microservices', 'DevOps'],
    topAzureSkills: ['Azure Sovereign Cloud', 'Terraform', 'Kubernetes', 'Microsoft Sentinel'],
    topCompanies: ['SAP', 'Delivery Hero', 'Zalando', 'BMW Tech', 'Siemens', 'N26'],
    hiringVelocity: 'Moderate'
  },
  {
    id: 'tokyo',
    city: 'Tokyo',
    country: 'Japan',
    region: 'Asia Pacific',
    coordinates: { x: 86, y: 38 },
    totalTechListings: 88000,
    avgSalaryUsd: 96000,
    costOfLivingIndex: 58,
    purchasingPowerScore: 88,
    remoteFriendlyPercent: 28,
    yoyHiringGrowth: 15.6,
    topHiringSpecialties: ['Digital Transformation (DX)', 'Robotics AI', 'Enterprise Cloud Infrastructure', 'Gaming'],
    topAzureSkills: ['Azure IoT Hub', 'Azure OpenAI (East Japan)', 'Synapse', 'Azure Arc'],
    topCompanies: ['Sony', 'Toyota Connected', 'Rakuten', 'NTT Data', 'SoftBank', 'Microsoft Japan'],
    hiringVelocity: 'High'
  },
  {
    id: 'toronto',
    city: 'Toronto, ON',
    country: 'Canada',
    region: 'North America',
    coordinates: { x: 26, y: 32 },
    totalTechListings: 82000,
    avgSalaryUsd: 124000,
    costOfLivingIndex: 72,
    purchasingPowerScore: 85,
    remoteFriendlyPercent: 45,
    yoyHiringGrowth: 13.5,
    topHiringSpecialties: ['AI Research & NLP', 'Banking Technology', 'Cloud Security', 'Healthcare Analytics'],
    topAzureSkills: ['Azure Machine Learning', 'AKS', 'Cosmos DB', 'Azure Monitor'],
    topCompanies: ['RBC Tech', 'Shopify', 'Vector Institute', 'Microsoft Canada', 'TD Bank'],
    hiringVelocity: 'High'
  },
  {
    id: 'singapore',
    city: 'Singapore',
    country: 'Singapore',
    region: 'Asia Pacific',
    coordinates: { x: 77, y: 58 },
    totalTechListings: 62000,
    avgSalaryUsd: 138000,
    costOfLivingIndex: 89,
    purchasingPowerScore: 87,
    remoteFriendlyPercent: 34,
    yoyHiringGrowth: 16.4,
    topHiringSpecialties: ['Fintech & Web3', 'APAC Cloud Infrastructure', 'AI Governance', 'Supply Chain Tech'],
    topAzureSkills: ['Azure OpenAI', 'Azure Arc', 'Synapse', 'ExpressRoute', 'Entra ID'],
    topCompanies: ['Grab', 'Sea Group', 'DBS Bank', 'Standard Chartered', 'Microsoft APAC', 'Shopee'],
    hiringVelocity: 'Very High'
  },
  {
    id: 'zurich',
    city: 'Zurich',
    country: 'Switzerland',
    region: 'Europe',
    coordinates: { x: 50, y: 31 },
    totalTechListings: 42000,
    avgSalaryUsd: 176000,
    costOfLivingIndex: 110,
    purchasingPowerScore: 92,
    remoteFriendlyPercent: 36,
    yoyHiringGrowth: 10.8,
    topHiringSpecialties: ['Fintech & Private Banking', 'Computer Vision & AI', 'High-Trust Cloud Architecture'],
    topAzureSkills: ['Azure Confidential Ledger', 'Azure OpenAI', 'AKS', 'Entra ID'],
    topCompanies: ['UBS', 'Credit Suisse', 'Google Zurich', 'Microsoft Switzerland', 'Roche', 'ABB'],
    hiringVelocity: 'Moderate'
  },
  {
    id: 'sydney',
    city: 'Sydney',
    country: 'Australia',
    region: 'Asia Pacific',
    coordinates: { x: 88, y: 78 },
    totalTechListings: 54000,
    avgSalaryUsd: 134000,
    costOfLivingIndex: 78,
    purchasingPowerScore: 86,
    remoteFriendlyPercent: 48,
    yoyHiringGrowth: 12.7,
    topHiringSpecialties: ['SaaS Scaling', 'Cloud Migration', 'Data Science & BI', 'DevSecOps'],
    topAzureSkills: ['Microsoft Fabric', 'Azure DevOps', 'Bicep', 'Azure Functions'],
    topCompanies: ['Atlassian', 'Canva', 'Commonwealth Bank', 'Macquarie Group', 'Microsoft ANZ'],
    hiringVelocity: 'High'
  }
];

export const azureCertProfiles: AzureCertProfile[] = [
  {
    code: 'AI-102',
    name: 'Azure AI Engineer Associate',
    level: 'Associate',
    iconColor: '#9333ea',
    medianSalaryBoostPercent: 28.5,
    avgAnnualSalary: 168000,
    activeJobOpenings: 42500,
    examDifficulty: 'Challenging',
    relatedRoles: ['AI Application Engineer', 'LLM Ops Specialist', 'Cognitive Solutions Architect'],
    topSkillTags: ['Azure OpenAI', 'Azure AI Search', 'Computer Vision', 'Speech Services', 'Document Intelligence'],
    summary: 'Validates ability to build, manage, and deploy AI solutions that leverage Azure OpenAI, Cognitive Services, and multi-modal knowledge retrieval.',
    recommendedLearningWeeks: 6
  },
  {
    code: 'AZ-305',
    name: 'Azure Solutions Architect Expert',
    level: 'Expert',
    iconColor: '#0078d4',
    medianSalaryBoostPercent: 32.0,
    avgAnnualSalary: 184000,
    activeJobOpenings: 68000,
    examDifficulty: 'Advanced',
    relatedRoles: ['Principal Cloud Architect', 'Enterprise Systems Architect', 'Chief Cloud Officer'],
    topSkillTags: ['Cloud Adoption Framework (CAF)', 'Well-Architected Framework', 'Multi-Region High Availability', 'Zero Trust', 'Governance'],
    summary: 'The gold standard for designing resilient, scalable, high-performance enterprise architectures across compute, storage, network, and security on Azure.',
    recommendedLearningWeeks: 10
  },
  {
    code: 'AZ-400',
    name: 'Azure DevOps Engineer Expert',
    level: 'Expert',
    iconColor: '#0ea5e9',
    medianSalaryBoostPercent: 24.5,
    avgAnnualSalary: 164000,
    activeJobOpenings: 56000,
    examDifficulty: 'Challenging',
    relatedRoles: ['Staff DevOps Engineer', 'Site Reliability Engineer (SRE)', 'Platform Engineer'],
    topSkillTags: ['Azure Pipelines', 'GitHub Actions', 'Terraform / Bicep', 'Continuous Compliance', 'ArgoCD / GitOps'],
    summary: 'Validates design and implementation of DevOps practices for version control, continuous integration, infrastructure as code, and automated security scans.',
    recommendedLearningWeeks: 8
  },
  {
    code: 'DP-203 / DP-600',
    name: 'Azure Data Engineer & Fabric Analytics',
    level: 'Associate',
    iconColor: '#10b981',
    medianSalaryBoostPercent: 26.0,
    avgAnnualSalary: 162000,
    activeJobOpenings: 61000,
    examDifficulty: 'Challenging',
    relatedRoles: ['Lead Data Engineer', 'Analytics Architect', 'Data Platform Specialist'],
    topSkillTags: ['Microsoft Fabric', 'Azure Synapse', 'OneLake', 'Azure Data Factory', 'PySpark', 'Delta Lake'],
    summary: 'Demonstrates expertise integrating, transforming, and consolidating data from structured and unstructured systems into enterprise analytics architectures.',
    recommendedLearningWeeks: 7
  },
  {
    code: 'SC-100',
    name: 'Cybersecurity Architect Expert',
    level: 'Expert',
    iconColor: '#ef4444',
    medianSalaryBoostPercent: 34.2,
    avgAnnualSalary: 189000,
    activeJobOpenings: 38000,
    examDifficulty: 'Advanced',
    relatedRoles: ['Chief Information Security Officer (CISO)', 'Lead Cloud Security Architect', 'SecOps Director'],
    topSkillTags: ['Zero Trust Architecture', 'Microsoft Sentinel', 'Defender for Cloud', 'Entra ID Privileged Identity', 'KQL'],
    summary: 'Designs holistic cybersecurity strategies and Zero Trust security architectures across hybrid and multi-cloud environments.',
    recommendedLearningWeeks: 9
  },
  {
    code: 'AZ-104',
    name: 'Azure Administrator Associate',
    level: 'Associate',
    iconColor: '#3b82f6',
    medianSalaryBoostPercent: 18.0,
    avgAnnualSalary: 136000,
    activeJobOpenings: 92000,
    examDifficulty: 'Moderate',
    relatedRoles: ['Azure Systems Administrator', 'Cloud Operations Engineer', 'Infrastructure Analyst'],
    topSkillTags: ['Virtual Networks', 'Azure RBAC', 'Storage Accounts', 'VM Scalesets', 'Azure Monitor'],
    summary: 'Foundational associate credential confirming hands-on ability to configure, manage, secure, and monitor compute, storage, and networking on Azure.',
    recommendedLearningWeeks: 5
  }
];

export const sampleJobPostings: JobPosting[] = [
  {
    id: 'job-msft-001',
    title: 'Principal Azure GenAI & LLM Platform Architect',
    company: 'Microsoft',
    companyTier: 'Big Tech',
    location: 'Redmond, WA (Hybrid / Remote Option)',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Hybrid',
    experienceLevel: 'Principal / Architect',
    salaryMin: 215000,
    salaryMax: 298000,
    salaryMedian: 256000,
    equityOffered: true,
    bonusPercent: 30,
    postedDate: 'Just now',
    skillsRequired: ['Azure OpenAI', 'Semantic Kernel', 'Python', 'Azure AI Search', 'LangChain', 'Prompt Flow', 'FastAPI'],
    azureServices: ['Azure OpenAI Service (GPT-4o)', 'Azure AI Search', 'Azure AI Studio', 'Cosmos DB', 'Azure Container Apps'],
    sector: 'AI & Deep Tech',
    description: 'Lead the architecture and design of enterprise generative AI platforms serving Global 500 customers across Microsoft Azure. Establish standards for multi-modal LLM evaluation, RAG pipelines, fine-tuning workflows, and cognitive safety layers.',
    responsibilities: [
      'Architect enterprise-grade RAG solutions using Azure OpenAI, Azure AI Search vector hybrid index, and Semantic Kernel.',
      'Define governance frameworks for LLM evaluation, prompt orchestration, token rate limits, and Azure AI Content Safety.',
      'Collaborate with executive engineering teams to migrate legacy heuristic search systems to modern neural embeddings.',
      'Design high-throughput, low-latency microservices deployed on Azure Container Apps and AKS.'
    ],
    qualifications: [
      '8+ years in software architecture with 3+ years hands-on with LLMs, Semantic Kernel, and Vector Search systems.',
      'Deep expertise in Python, C# / .NET, and Azure OpenAI APIs.',
      'Proven track record implementing production vector embeddings and hybrid re-ranking.'
    ],
    benefits: ['Full Health/Dental/Vision', 'Generous 401(k) Match (50% up to limit)', '$45,000+ Annual Stock Grant (RSUs)', 'Annual Learning & Azure Cert Stipend ($5,000)'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-oai-002',
    title: 'Staff LLM Systems & Distributed Inference Engineer',
    company: 'OpenAI',
    companyTier: 'Big Tech',
    location: 'San Francisco, CA (Hybrid)',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Hybrid',
    experienceLevel: 'Lead / Staff',
    salaryMin: 245000,
    salaryMax: 370000,
    salaryMedian: 310000,
    equityOffered: true,
    bonusPercent: 25,
    postedDate: '1 hour ago',
    skillsRequired: ['PyTorch', 'CUDA', 'Python', 'Azure Kubernetes Service (AKS)', 'NVIDIA Triton', 'Distributed Systems'],
    azureServices: ['Azure NDv5 H100 Superclusters', 'AKS GPU Node Pools', 'Azure Blob Storage', 'InfiniBand Fabric'],
    sector: 'AI & Deep Tech',
    description: 'Scale next-generation distributed LLM inference clusters hosted on Azure NVIDIA H100 supercomputers. Optimize throughput, token latency (TTFT / ITL), KV-cache offloading, and continuous batching.',
    responsibilities: [
      'Build and optimize distributed inference runtimes using vLLM, TensorRT-LLM, and Triton Inference Server.',
      'Manage GPU cluster health, automatic node remediation, and telemetry across thousands of Azure H100 GPUs.',
      'Implement multi-tier KV-cache paging and dynamic speculative decoding algorithms.',
      'Profile CUDA kernels to squeeze maximum FLOP utilization out of modern tensor cores.'
    ],
    qualifications: [
      '6+ years in high-performance computing, low-level systems engineering, or distributed ML inference.',
      'Expert proficiency in C++, Python, and PyTorch.',
      'Deep understanding of transformer model architectures and GPU memory bandwidth bottlenecks.'
    ],
    benefits: ['Comprehensive Healthcare (100% covered)', 'Substantial Equity Ownership Package', 'Unlimited PTO & Sabbaticals', 'Daily Gourmet Catered Meals'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-goog-003',
    title: 'Staff Cloud Infrastructure & Kubernetes Architect',
    company: 'Google Cloud',
    companyTier: 'Big Tech',
    location: 'Sunnyvale, CA / Seattle, WA',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Hybrid',
    experienceLevel: 'Principal / Architect',
    salaryMin: 210000,
    salaryMax: 295000,
    salaryMedian: 252000,
    equityOffered: true,
    bonusPercent: 25,
    postedDate: '3 hours ago',
    skillsRequired: ['Kubernetes', 'Go', 'Terraform', 'Distributed Systems', 'eBPF', 'Multi-Cloud Networking'],
    azureServices: ['AKS Federation', 'Azure Virtual WAN', 'ExpressRoute Multi-Cloud Interconnect'],
    sector: 'Cloud & Enterprise SaaS',
    description: 'Architect large-scale hybrid cloud interconnects and container orchestrators bridging Google Cloud and enterprise Microsoft Azure landing zones.',
    responsibilities: [
      'Lead design of hybrid multi-cloud control planes orchestrating 100,000+ container workloads.',
      'Build low-latency cross-cloud routing fabrics with sub-15ms interconnect SLAs.',
      'Enforce zero-trust identity federation between Google Cloud IAM and Microsoft Entra ID.',
      'Mentor senior engineers across systems reliability and disaster recovery planning.'
    ],
    qualifications: [
      '8+ years in cloud infrastructure, site reliability engineering, or distributed systems.',
      'Deep expertise in Go, Kubernetes internals, and Linux kernel networking (eBPF).',
      'Track record leading multi-million dollar cloud transformations.'
    ],
    benefits: ['Top-tier Google GSU Equity Grant', 'Comprehensive Medical/Dental/Vision', '401(k) 50% match', 'On-site Wellness & Fitness Centers'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-nvda-004',
    title: 'Senior Accelerated Computing & Cloud AI Engineer',
    company: 'NVIDIA',
    companyTier: 'Big Tech',
    location: 'Santa Clara, CA (Hybrid / Remote Option)',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Hybrid',
    experienceLevel: 'Senior',
    salaryMin: 185000,
    salaryMax: 265000,
    salaryMedian: 225000,
    equityOffered: true,
    bonusPercent: 20,
    postedDate: '5 hours ago',
    skillsRequired: ['CUDA', 'C++', 'Python', 'NVIDIA NIM', 'Azure Machine Learning', 'Docker', 'Kubernetes'],
    azureServices: ['Azure ML Managed Compute', 'AKS GPU Pools (H100/H200)', 'Azure Container Registry'],
    sector: 'AI & Deep Tech',
    description: 'Integrate NVIDIA NIM microservices and TensorRT-LLM runtimes natively into Microsoft Azure AI infrastructure, delivering 5x inference acceleration for enterprise generative AI.',
    responsibilities: [
      'Optimize NVIDIA containerized microservices for deployment on Azure Container Apps and AKS.',
      'Collaborate with Microsoft Azure engineers to benchmark GPU driver stacks and InfiniBand fabrics.',
      'Implement automated load testing frameworks measuring token generation throughput and P99 latency.',
      'Author technical whitepapers and reference architectures for enterprise AI developers.'
    ],
    qualifications: [
      '5+ years experience in GPU-accelerated computing, CUDA programming, or ML platforms.',
      'Proficiency in C++, Python, and container runtimes.',
      'Experience with Azure ML or Kubernetes orchestration.'
    ],
    benefits: ['NVIDIA Employee Stock Purchase Plan (ESPP)', '401(k) Match', 'Comprehensive Healthcare', 'Flexible Time Off'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-jpmc-005',
    title: 'Lead Cloud Security Architect & Zero Trust Strategist',
    company: 'JPMorgan Chase & Co.',
    companyTier: 'Enterprise 500',
    location: 'New York, NY (Hybrid)',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Hybrid',
    experienceLevel: 'Lead / Staff',
    salaryMin: 190000,
    salaryMax: 260000,
    salaryMedian: 225000,
    equityOffered: true,
    bonusPercent: 25,
    postedDate: '6 hours ago',
    skillsRequired: ['Microsoft Sentinel', 'Defender for Cloud', 'Entra ID P2', 'KQL', 'Zero Trust', 'Confidential Computing'],
    azureServices: ['Microsoft Sentinel SIEM/SOAR', 'Azure Confidential Ledger', 'Azure Key Vault HSM', 'Azure Policy'],
    sector: 'Fintech & Quant',
    description: 'Design and execute multi-tenant cloud security architecture protecting trillions of dollars in daily global asset transactions across Microsoft Azure financial landing zones.',
    responsibilities: [
      'Architect Zero-Trust security perimeters leveraging Microsoft Entra ID Privileged Identity Management (PIM).',
      'Build automated SIEM detection and SOAR incident response playbooks using Microsoft Sentinel and KQL.',
      'Enforce hardware-encrypted Confidential Computing on Azure VMs for high-frequency trading data.',
      'Audit regulatory compliance against FedRAMP High, SEC, and Basel III frameworks.'
    ],
    qualifications: [
      '7+ years in enterprise information security and cloud architecture.',
      'Expertise in Microsoft Sentinel, KQL threat hunting, and Azure security services.',
      'SC-100 or CISSP certification strongly desired.'
    ],
    benefits: ['Generous Annual Discretionary Bonus', 'Comprehensive Health & Retirement Plans', 'Tuition & Cert Reimbursement', 'Commuter Transit Subsidy'],
    visaSponsorship: false,
    workPermitRequired: true
  },
  {
    id: 'job-dbrx-006',
    title: 'Staff Lakehouse & Microsoft Fabric Architect',
    company: 'Databricks',
    companyTier: 'Big Tech',
    location: 'San Francisco, CA / Seattle, WA (Remote OK)',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Remote-First',
    experienceLevel: 'Lead / Staff',
    salaryMin: 195000,
    salaryMax: 270000,
    salaryMedian: 232000,
    equityOffered: true,
    bonusPercent: 20,
    postedDate: '12 hours ago',
    skillsRequired: ['PySpark', 'Delta Lake', 'Microsoft Fabric', 'OneLake', 'Azure Data Factory', 'SQL', 'Python'],
    azureServices: ['Azure Databricks', 'Microsoft Fabric OneLake', 'Azure Data Lake Gen2', 'Azure Synapse'],
    sector: 'Cloud & Enterprise SaaS',
    description: 'Pioneer the unified Data + AI Lakehouse integration connecting Azure Databricks, Microsoft Fabric OneLake, and real-time streaming analytics for Fortune 50 clients.',
    responsibilities: [
      'Architect petabyte-scale Delta Lakehouse pipelines with Unity Catalog governance and row-level security.',
      'Optimize PySpark cluster configurations for low-latency BI queries and real-time stream ingestion.',
      'Develop bi-directional data pipelines bridging Azure Databricks with Microsoft Fabric OneLake.',
      'Guide enterprise data platform teams on Medallion architecture patterns and cost governance.'
    ],
    qualifications: [
      '6+ years experience in distributed data systems, Apache Spark, and cloud data architecture.',
      'Deep expertise in PySpark, Delta Lake, SQL, and Azure cloud storage.',
      'Hands-on experience with Microsoft Fabric or Azure Databricks.'
    ],
    benefits: ['Substantial Pre-IPO Equity Allocation', '100% Paid Health Benefits', 'Unlimited PTO', '$3,000 Annual Learning Budget'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-meta-007',
    title: 'Senior Full-Stack Cloud & TypeScript Engineer',
    company: 'Meta',
    companyTier: 'Big Tech',
    location: 'Menlo Park, CA / Remote',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Remote-First',
    experienceLevel: 'Senior',
    salaryMin: 180000,
    salaryMax: 250000,
    salaryMedian: 215000,
    equityOffered: true,
    bonusPercent: 20,
    postedDate: '18 hours ago',
    skillsRequired: ['React 19', 'TypeScript', 'GraphQL', 'Node.js', 'Azure App Service', 'REST APIs', 'PostgreSQL'],
    azureServices: ['Azure App Service', 'Azure Static Web Apps', 'Azure Cosmos DB', 'Azure Front Door'],
    sector: 'Cloud & Enterprise SaaS',
    description: 'Build enterprise advertising analytics, creative optimization workflows, and high-concurrency dashboards utilized by millions of global business advertisers.',
    responsibilities: [
      'Develop reactive web interfaces using React 19, TypeScript, and Relay / GraphQL with sub-100ms render speeds.',
      'Design fault-tolerant microservices in Node.js / Go deployed across multi-region cloud services.',
      'Optimize complex database queries and real-time WebSocket state synchronizers.',
      'Drive accessibility (a11y) and Core Web Vitals optimization across all user-facing properties.'
    ],
    qualifications: [
      '5+ years building production web applications with React, TypeScript, and modern backend APIs.',
      'Strong grasp of state management, client-side caching, and distributed systems.',
      'B.S. in Computer Science or equivalent practical experience.'
    ],
    benefits: ['Meta RSU Equity Grant', 'Comprehensive Medical/Dental/Vision', '401(k) Match', 'Wellness & Productivity Stipend'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-strp-008',
    title: 'Staff Distributed Systems & Financial Platform Engineer',
    company: 'Stripe',
    companyTier: 'Big Tech',
    location: 'San Francisco, CA / Seattle / Remote',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Remote-First',
    experienceLevel: 'Lead / Staff',
    salaryMin: 205000,
    salaryMax: 285000,
    salaryMedian: 245000,
    equityOffered: true,
    bonusPercent: 20,
    postedDate: '1 day ago',
    skillsRequired: ['Go', 'Rust', 'Kubernetes', 'Cosmos DB', 'Kafka', 'Distributed Systems', 'Zero-Trust'],
    azureServices: ['Azure Cosmos DB', 'Azure Service Bus', 'Azure Front Door', 'Azure Key Vault'],
    sector: 'Fintech & Quant',
    description: 'Build the core payment ledger and settlement rails processing hundreds of billions in global online commerce with 99.999% availability and immutable idempotency.',
    responsibilities: [
      'Design distributed ledger engines in Go and Rust with strict linearizable consistency guarantees.',
      'Optimize multi-region database replication on Azure Cosmos DB sustaining 80,000+ peak TPS.',
      'Implement automated chaos engineering tests simulating datacenter partition and failover.',
      'Ensure zero-downtime database schema migrations and automated reconciliation.'
    ],
    qualifications: [
      '7+ years in distributed systems engineering, payment rails, or high-throughput financial infrastructure.',
      'Proficiency in Go, Rust, or Java with deep concurrency knowledge.',
      'Expertise in transaction isolation levels, Raft/Paxos consensus, and distributed databases.'
    ],
    benefits: ['Stripe Equity Grant', 'Flexible Remote Work Setup ($2,000 allowance)', 'Comprehensive Healthcare', 'Learning & Development Stipend'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-aapl-009',
    title: 'Senior Cloud Operations & SRE Specialist',
    company: 'Apple',
    companyTier: 'Big Tech',
    location: 'Cupertino, CA / Austin, TX',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Hybrid',
    experienceLevel: 'Senior',
    salaryMin: 175000,
    salaryMax: 245000,
    salaryMedian: 210000,
    equityOffered: true,
    bonusPercent: 18,
    postedDate: '1 day ago',
    skillsRequired: ['Terraform', 'Azure Kubernetes Service (AKS)', 'Python', 'Prometheus', 'Grafana', 'Linux'],
    azureServices: ['AKS', 'Azure Monitor', 'Azure Virtual Networks', 'Log Analytics'],
    sector: 'Cloud & Enterprise SaaS',
    description: 'Support high-scale media distribution, iCloud backend microservices, and global push notification infrastructure maintaining five-nines uptime.',
    responsibilities: [
      'Standardize Infrastructure as Code across multi-region Kubernetes clusters using Terraform and Bicep.',
      'Implement real-time Prometheus alerting and distributed OpenTelemetry tracing across 500+ microservices.',
      'Conduct automated capacity forecasting and disaster recovery drill simulations.',
      'Automate incident remediation workflows reducing Mean Time to Resolution (MTTR) by 60%.'
    ],
    qualifications: [
      '5+ years in SRE, DevOps, or Cloud Infrastructure engineering at enterprise scale.',
      'Hands-on expertise with Kubernetes, Linux kernel internals, and Python/Go scripting.',
      'AZ-400 or CKA certification preferred.'
    ],
    benefits: ['Apple RSU Equity Grant', 'Apple Product Discounts (25%+ off)', 'Comprehensive Health & 401(k) Match', 'On-site Health Centers'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-snfl-010',
    title: 'Principal Data Platform & Cloud Analytics Architect',
    company: 'Snowflake',
    companyTier: 'Big Tech',
    location: 'Bellevue, WA / San Mateo, CA',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Hybrid',
    experienceLevel: 'Principal / Architect',
    salaryMin: 220000,
    salaryMax: 305000,
    salaryMedian: 262000,
    equityOffered: true,
    bonusPercent: 25,
    postedDate: '2 days ago',
    skillsRequired: ['Snowflake', 'SQL', 'Python', 'PySpark', 'Azure Data Factory', 'OneLake', 'Data Governance'],
    azureServices: ['Azure Blob Storage', 'Azure Data Factory', 'Azure Event Hubs', 'Azure Purview'],
    sector: 'Cloud & Enterprise SaaS',
    description: 'Architect multi-cloud data warehousing and real-time streaming architectures on Microsoft Azure for Fortune 100 enterprise clients.',
    responsibilities: [
      'Design automated streaming ingestion from Azure Event Hubs into Snowflake Dynamic Tables.',
      'Implement enterprise data mesh governance with column-level security and row access policies.',
      'Benchmark warehouse compute efficiency, query pruning, and storage optimization.',
      'Partner with enterprise CDOs to guide legacy data warehouse migrations to modern Data Clouds.'
    ],
    qualifications: [
      '8+ years in enterprise data warehousing, cloud architecture, and big data engineering.',
      'Expert knowledge of SQL, Python, and cloud storage topologies.',
      'Proven leadership in high-scale data platform modernization.'
    ],
    benefits: ['Snowflake RSU Package', 'Full Medical/Dental/Vision', '401(k) Match', 'Generous Wellness Stipend'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-nflx-011',
    title: 'Senior MLOps & Recommendation Systems Engineer',
    company: 'Netflix',
    companyTier: 'Big Tech',
    location: 'Los Gatos, CA / Remote',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Remote-First',
    experienceLevel: 'Senior',
    salaryMin: 230000,
    salaryMax: 340000,
    salaryMedian: 285000,
    equityOffered: true,
    bonusPercent: 0, // Netflix top of market all-cash model option
    postedDate: '2 days ago',
    skillsRequired: ['Python', 'PyTorch', 'Ray', 'Kubernetes', 'MLflow', 'Feature Store', 'Kafka'],
    azureServices: ['Azure Machine Learning', 'AKS GPU Clusters', 'Azure Cosmos DB', 'Event Hubs'],
    sector: 'AI & Deep Tech',
    description: 'Scale personalization, ranking algorithms, and artwork recommendation models serving over 280 million global subscribers with sub-30ms P99 latency.',
    responsibilities: [
      'Deploy automated continuous training pipelines utilizing Ray and PyTorch on GPU clusters.',
      'Maintain real-time feature store processing 2M+ read/write operations per second.',
      'Implement automated multi-armed bandit experimentation for continuous algorithmic iteration.',
      'Monitor live model drift and statistical anomaly detection in production recommendation streams.'
    ],
    qualifications: [
      '5+ years in production Machine Learning engineering, MLOps, or distributed ranking systems.',
      'Proficiency in Python, PyTorch, Ray, and high-scale streaming data.',
      'Deep understanding of recommendation algorithms and embedding retrieval.'
    ],
    benefits: ['Top-of-Market All-Cash Compensation Option', 'Stock Option Program', 'Unlimited Vacation Policy', 'Comprehensive Family Medical'],
    visaSponsorship: true,
    workPermitRequired: false
  },
  {
    id: 'job-pltr-012',
    title: 'Lead AIP & Autonomous AI Solutions Architect',
    company: 'Palantir Technologies',
    companyTier: 'Enterprise 500',
    location: 'Denver, CO / New York / Washington D.C.',
    country: 'United States',
    region: 'North America',
    remotePolicy: 'Hybrid',
    experienceLevel: 'Lead / Staff',
    salaryMin: 185000,
    salaryMax: 260000,
    salaryMedian: 222000,
    equityOffered: true,
    bonusPercent: 20,
    postedDate: '3 days ago',
    skillsRequired: ['Palantir Foundry', 'Azure OpenAI', 'Python', 'TypeScript', 'Ontology Modeling', 'Zero Trust'],
    azureServices: ['Azure Government Cloud', 'Azure OpenAI', 'Azure Confidential Computing', 'Entra ID'],
    sector: 'AI & Deep Tech',
    description: 'Deploy Palantir Artificial Intelligence Platform (AIP) integrated with Azure OpenAI and high-security government/enterprise ontologies to enable autonomous decision operations.',
    responsibilities: [
      'Architect enterprise ontology models linking disparate transactional systems into real-time digital twins.',
      'Integrate Azure OpenAI LLM agents with strict deterministic guardrails and audit logging.',
      'Deploy secure multi-tenant pipelines inside Azure Government and IL5/IL6 compliant environments.',
      'Collaborate on-site with executive defense and enterprise leadership to operationalize AI workflows.'
    ],
    qualifications: [
      '6+ years in solutions architecture, enterprise software deployment, or technical consulting.',
      'Strong programming proficiency in Python, TypeScript, and SQL.',
      'Ability to obtain and maintain a U.S. Security Clearance if required.'
    ],
    benefits: ['Palantir Equity Package', 'Comprehensive Health/Dental/Vision', '401(k) Match', 'Generous Commuter & Relocation Support'],
    visaSponsorship: false,
    workPermitRequired: true
  }
];

export const skillRelationshipNodes = [
  { id: 'azure-openai', label: 'Azure OpenAI', category: 'AI', x: 280, y: 180, radius: 28, color: '#9333ea', demand: 99 },
  { id: 'semantic-kernel', label: 'Semantic Kernel', category: 'AI', x: 380, y: 120, radius: 22, color: '#a855f7', demand: 97 },
  { id: 'azure-ai-search', label: 'Azure AI Search', category: 'AI', x: 220, y: 280, radius: 24, color: '#3b82f6', demand: 95 },
  { id: 'python', label: 'Python', category: 'Language', x: 420, y: 250, radius: 26, color: '#eab308', demand: 98 },
  { id: 'aks', label: 'Azure Kubernetes (AKS)', category: 'DevOps', x: 160, y: 400, radius: 28, color: '#0284c7', demand: 96 },
  { id: 'terraform', label: 'Terraform & IaC', category: 'DevOps', x: 260, y: 460, radius: 24, color: '#6366f1', demand: 91 },
  { id: 'azure-bicep', label: 'Azure Bicep', category: 'DevOps', x: 120, y: 520, radius: 20, color: '#0ea5e9', demand: 86 },
  { id: 'microsoft-fabric', label: 'Microsoft Fabric', category: 'Data', x: 540, y: 340, radius: 26, color: '#10b981', demand: 93 },
  { id: 'synapse', label: 'Azure Synapse', category: 'Data', x: 620, y: 260, radius: 22, color: '#059669', demand: 89 },
  { id: 'pyspark', label: 'PySpark / Delta', category: 'Data', x: 520, y: 440, radius: 22, color: '#f59e0b', demand: 94 },
  { id: 'cosmos-db', label: 'Cosmos DB', category: 'Data', x: 360, y: 360, radius: 24, color: '#06b6d4', demand: 89 },
  { id: 'sentinel', label: 'Microsoft Sentinel', category: 'Security', x: 680, y: 150, radius: 24, color: '#ef4444', demand: 94 },
  { id: 'entra-id', label: 'Entra ID (Zero Trust)', category: 'Security', x: 740, y: 240, radius: 22, color: '#dc2626', demand: 92 },
  { id: 'kql', label: 'KQL Analytics', category: 'Security', x: 780, y: 130, radius: 18, color: '#f43f5e', demand: 88 },
  { id: 'dotnet-csharp', label: '.NET 8 / C#', category: 'Backend', x: 440, y: 480, radius: 24, color: '#8b5cf6', demand: 91 },
  { id: 'react-ts', label: 'React & TypeScript', category: 'Frontend', x: 320, y: 560, radius: 22, color: '#38bdf8', demand: 90 }
];

export const skillRelationshipEdges = [
  { source: 'azure-openai', target: 'semantic-kernel', weight: 0.95 },
  { source: 'azure-openai', target: 'azure-ai-search', weight: 0.92 },
  { source: 'azure-openai', target: 'python', weight: 0.88 },
  { source: 'azure-openai', target: 'cosmos-db', weight: 0.74 },
  { source: 'azure-ai-search', target: 'cosmos-db', weight: 0.82 },
  { source: 'semantic-kernel', target: 'dotnet-csharp', weight: 0.86 },
  { source: 'aks', target: 'terraform', weight: 0.90 },
  { source: 'aks', target: 'azure-bicep', weight: 0.82 },
  { source: 'terraform', target: 'azure-bicep', weight: 0.76 },
  { source: 'microsoft-fabric', target: 'synapse', weight: 0.94 },
  { source: 'microsoft-fabric', target: 'pyspark', weight: 0.91 },
  { source: 'synapse', target: 'pyspark', weight: 0.89 },
  { source: 'pyspark', target: 'python', weight: 0.92 },
  { source: 'sentinel', target: 'entra-id', weight: 0.96 },
  { source: 'sentinel', target: 'kql', weight: 0.98 },
  { source: 'entra-id', target: 'aks', weight: 0.72 },
  { source: 'dotnet-csharp', target: 'cosmos-db', weight: 0.85 },
  { source: 'dotnet-csharp', target: 'react-ts', weight: 0.78 }
];
