import React, { useState } from 'react';
import {
  Sparkles,
  Award,
  Target,
  ArrowRight,
  TrendingUp,
  CheckCircle2,
  AlertTriangle,
  BookOpen,
  Calendar,
  Layers,
  Download,
  RotateCcw,
  Zap,
  ShieldCheck
} from 'lucide-react';
import { azureService } from '../../services/azureService';
import { SkillGapResult } from '../../types/market';
import { formatSalary } from '../../utils/formatters';
import { downloadMarkdownReport } from '../../utils/exportUtils';

const presetProfiles = [
  {
    name: 'Full-Stack Developer',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker', 'REST APIs', 'Git'],
    exp: 4,
    defaultTarget: 'Lead Azure GenAI & LLM Solutions Architect'
  },
  {
    name: 'Cloud & DevOps Admin',
    skills: ['Linux', 'Bash', 'Basic Azure', 'Docker', 'CI/CD', 'Git', 'Python'],
    exp: 3,
    defaultTarget: 'Principal Cloud Platform & Kubernetes (AKS) Engineer'
  },
  {
    name: 'Data Analyst / SQL Specialist',
    skills: ['SQL', 'Power BI', 'Excel', 'Python', 'Pandas', 'Basic ETL'],
    exp: 3,
    defaultTarget: 'Senior Microsoft Fabric & Data Engineering Specialist'
  },
  {
    name: 'Security Operations Analyst',
    skills: ['Network Security', 'Firewalls', 'Incident Triage', 'Python', 'Splunk'],
    exp: 3,
    defaultTarget: 'Staff Cloud Security & Zero Trust Architect'
  }
];

const targetRoles = [
  'Lead Azure GenAI & LLM Solutions Architect',
  'Principal Cloud Platform & Kubernetes (AKS) Engineer',
  'Senior Microsoft Fabric & Data Engineering Specialist',
  'Staff Cloud Security & Zero Trust Architect',
  'Principal Azure Solutions Architect (AZ-305)',
  'Lead Azure Cloud Migration Consultant'
];

export const SkillGapAnalyzer: React.FC = () => {
  const [skillInput, setSkillInput] = useState<string>(presetProfiles[0].skills.join(', '));
  const [selectedTargetRole, setSelectedTargetRole] = useState<string>(presetProfiles[0].defaultTarget);
  const [experienceYears, setExperienceYears] = useState<number>(4);
  const [analyzing, setAnalyzing] = useState<boolean>(false);
  const [result, setResult] = useState<SkillGapResult | null>(null);

  const handleSelectPreset = (preset: typeof presetProfiles[0]) => {
    setSkillInput(preset.skills.join(', '));
    setSelectedTargetRole(preset.defaultTarget);
    setExperienceYears(preset.exp);
    setResult(null);
  };

  const handleRunAnalysis = async () => {
    if (!skillInput.trim()) return;
    setAnalyzing(true);
    const skillsArray = skillInput.split(',').map(s => s.trim()).filter(Boolean);
    const diagnostic = await azureService.analyzeSkillGap(skillsArray, selectedTargetRole, experienceYears);
    setResult(diagnostic);
    setAnalyzing(false);
  };

  const handleExportRoadmap = () => {
    if (!result) return;
    const md = `# Azure AI Upskilling Roadmap: ${result.targetRole}

**Match Readiness**: ${result.matchPercentage}%
**Current Estimated Base**: ${formatSalary(result.currentEstimatedSalary)}
**Target Role Potential**: ${formatSalary(result.potentialTargetSalary)}
**Estimated Salary Leap**: +${formatSalary(result.estimatedSalaryDelta)}

---

## 🎯 Executive Diagnostic Summary
${result.summaryAnalysis}

## 🔍 Critical Priority Skill Gaps
${result.criticalMissingSkills
  .map(
    s =>
      `- **${s.skill}** (${s.importance} Priority) -> Salary Impact: ${s.impactOnSalary}\n  *Resource*: ${s.learningResource}`
  )
  .join('\n\n')}

---

## 📅 12-Week Accelerated Learning Pathway

${result.roadmap
  .map(
    m => `### 🚩 ${m.phaseTitle} (${m.weekRange})
**Focus**: ${m.focus}
**Capstone Deliverable**: \`${m.deliverableProject}\`
**Azure Resources**: ${m.azureResources.join(', ')}
**Key Topics**: ${m.keyTopics.join(' • ')}`
  )
  .join('\n\n')}

---
*Generated by Azure TalentPulse AI Advisor*`;

    downloadMarkdownReport(`azure-roadmap-${result.targetRole.toLowerCase().replace(/[^a-z0-9]/g, '-')}.md`, md);
  };

  return (
    <div className="w-full space-y-10 animate-fade-in flex flex-col items-center">
      {/* Header */}
      <div className="w-full flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-[var(--border-color)] text-center sm:text-left">
        <div className="space-y-2">
          <div className="flex items-center justify-center sm:justify-start gap-2.5">
            <h2 className="text-2xl sm:text-3xl font-extrabold text-[var(--text-primary)] tracking-tight mb-1">
              AI Skill Gap Diagnostic & Career Pathway
            </h2>
            <span className="azure-badge">AI Career Engine</span>
          </div>
          <p className="text-sm text-[var(--text-secondary)] leading-relaxed">
            Analyze your current stack against enterprise cloud requirements and generate a personalized 12-week roadmap.
          </p>
        </div>
      </div>

      {/* Input Setup Card */}
      <div className="w-full saas-card p-8 sm:p-10 rounded-3xl space-y-6">
        <div className="text-center sm:text-left">
          <span className="text-xs font-bold uppercase tracking-wider text-[var(--text-muted)] block mb-3">
            Step 1: Choose a Sample Preset or Enter Your Own Skills
          </span>
          <div className="flex flex-wrap items-center justify-center sm:justify-start gap-2.5">
            {presetProfiles.map(preset => (
              <button
                key={preset.name}
                onClick={() => handleSelectPreset(preset)}
                className="px-4 py-2 rounded-xl bg-[var(--bg-surface-subtle)] hover:bg-[var(--bg-surface-hover)] border border-[var(--border-color)] text-xs font-bold text-[var(--text-primary)] transition flex items-center gap-2"
              >
                <Zap className="w-3.5 h-3.5 text-amber-400" />
                <span>{preset.name}</span>
              </button>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 pt-4 border-t border-[var(--border-color)]">
          {/* Left Column: Skills & Experience */}
          <div className="lg:col-span-7 space-y-5">
            <div>
              <label className="block text-xs font-bold text-[var(--text-primary)] mb-2">
                Your Technical Skills (comma-separated):
              </label>
              <textarea
                rows={3}
                value={skillInput}
                onChange={e => setSkillInput(e.target.value)}
                placeholder="e.g. React, TypeScript, Python, Docker, PostgreSQL, Linux, Git..."
                className="w-full bg-[var(--bg-surface-subtle)] border border-[var(--border-color)] rounded-2xl p-4 text-xs font-mono text-[var(--text-primary)] placeholder-slate-500 focus:outline-none focus:border-blue-500 leading-relaxed"
              />
            </div>

            <div>
              <div className="flex justify-between text-xs font-bold text-[var(--text-primary)] mb-2">
                <span>Years of Professional Experience</span>
                <span className="text-sky-400 font-mono font-bold">{experienceYears} Years</span>
              </div>
              <input
                type="range"
                min={0}
                max={15}
                value={experienceYears}
                onChange={e => setExperienceYears(Number(e.target.value))}
                className="w-full h-2.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-blue-500"
              />
            </div>
          </div>

          {/* Right Column: Target Role & CTA */}
          <div className="lg:col-span-5 flex flex-col justify-between space-y-5">
            <div>
              <label className="block text-xs font-bold text-[var(--text-primary)] mb-2">
                Target High-Comp Cloud Role:
              </label>
              <select
                value={selectedTargetRole}
                onChange={e => setSelectedTargetRole(e.target.value)}
                className="w-full bg-[var(--bg-surface-subtle)] border border-[var(--border-color)] rounded-2xl px-4 py-3 text-xs font-bold text-[var(--text-primary)] focus:outline-none focus:border-blue-500"
              >
                {targetRoles.map(role => (
                  <option key={role} value={role}>
                    {role}
                  </option>
                ))}
              </select>
            </div>

            <button
              onClick={handleRunAnalysis}
              disabled={analyzing || !skillInput.trim()}
              className="w-full azure-btn-primary py-4 text-sm font-bold flex items-center justify-center gap-2.5 shadow-lg shadow-blue-500/25"
            >
              {analyzing ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  <span>Evaluating Azure Skill Graph...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  <span>Run AI Skill Gap Diagnostic</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Diagnostic Results Section */}
      {result && (
        <div className="w-full space-y-8 animate-fade-in">
          {/* Match Score & Financial Summary */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Score Card */}
            <div className="saas-card p-6 rounded-3xl flex items-center gap-5">
              <div className="relative flex items-center justify-center w-20 h-20 shrink-0">
                <svg className="w-full h-full" viewBox="0 0 36 36">
                  <path
                    className="text-slate-800"
                    strokeWidth="3.5"
                    stroke="currentColor"
                    fill="none"
                    d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                  />
                  <path
                    className={
                      result.matchPercentage >= 70
                        ? 'text-emerald-400'
                        : result.matchPercentage >= 45
                        ? 'text-sky-400'
                        : 'text-amber-400'
                    }
                    strokeDasharray={`${result.matchPercentage}, 100`}
                    strokeWidth="3.5"
                    strokeLinecap="round"
                    stroke="currentColor"
                    fill="none"
                    d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                  />
                </svg>
                <div className="absolute flex flex-col items-center">
                  <span className="text-lg font-extrabold text-[var(--text-primary)] font-mono leading-none">
                    {result.matchPercentage}%
                  </span>
                  <span className="text-[9px] text-[var(--text-muted)] font-bold">Match</span>
                </div>
              </div>

              <div>
                <span className="text-xs font-bold text-[var(--text-muted)] block uppercase tracking-wider mb-1">
                  Target Role Readiness
                </span>
                <h3 className="text-sm font-bold text-[var(--text-primary)] mt-1 mb-1">{result.targetRole}</h3>
                <span className="text-xs text-emerald-400 mt-1 block font-semibold leading-relaxed">
                  {result.currentStrengths.length} core competencies matched
                </span>
              </div>
            </div>

            {/* Compensation Leap Card */}
            <div className="saas-card p-6 rounded-3xl flex flex-col justify-between space-y-2">
              <span className="text-xs font-bold text-[var(--text-muted)] uppercase tracking-wider block mb-1">
                Estimated Annual Income Leap
              </span>
              <div className="flex items-baseline gap-2 mb-1">
                <span className="text-3xl font-extrabold text-emerald-400 font-mono">
                  +{formatSalary(result.estimatedSalaryDelta)}
                </span>
                <span className="text-xs text-[var(--text-muted)]">/ year increase</span>
              </div>
              <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
                From ~{formatSalary(result.currentEstimatedSalary)} to {formatSalary(result.potentialTargetSalary)}
              </p>
            </div>

            {/* Action Bar Card */}
            <div className="saas-card p-6 rounded-3xl flex flex-col justify-between space-y-3">
              <span className="text-xs font-bold text-[var(--text-muted)] uppercase tracking-wider block mb-1">
                Export Your Learning Plan
              </span>
              <p className="text-xs text-[var(--text-secondary)] leading-relaxed mb-2">
                Download your complete week-by-week curriculum with official Microsoft Learn guides.
              </p>
              <button
                onClick={handleExportRoadmap}
                className="azure-btn-secondary text-xs w-full flex items-center justify-center gap-2"
              >
                <Download className="w-4 h-4 text-sky-400" />
                <span>Download Roadmap (Markdown)</span>
              </button>
            </div>
          </div>

          {/* AI Executive Analysis */}
          <div className="saas-card p-7 rounded-3xl border-blue-500/30 space-y-2">
            <div className="flex items-center gap-2 text-sky-400 font-bold text-sm mb-1">
              <Sparkles className="w-4 h-4" />
              <span>Azure AI Executive Diagnostic</span>
            </div>
            <p className="text-xs sm:text-sm text-[var(--text-secondary)] leading-loose">{result.summaryAnalysis}</p>
          </div>

          {/* Critical Skill Gaps */}
          <div className="saas-card p-8 rounded-3xl space-y-6">
            <div className="flex items-center justify-between pb-3 border-b border-[var(--border-color)]">
              <div className="flex items-center gap-2.5">
                <Target className="w-5 h-5 text-rose-400" />
                <h3 className="text-base font-bold text-[var(--text-primary)] mb-1">
                  Critical Priority Skill Gaps
                </h3>
              </div>
              <span className="text-xs text-[var(--text-muted)]">Ordered by salary leverage</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {result.criticalMissingSkills.map(gap => (
                <div
                  key={gap.skill}
                  className="p-5 rounded-2xl bg-[var(--bg-surface-subtle)] border border-[var(--border-color)] flex flex-col justify-between space-y-4"
                >
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-bold text-[var(--text-primary)] mb-1">{gap.skill}</span>
                        <span
                          className={`text-[9px] font-bold px-2 py-0.5 rounded-full border ${
                            gap.importance === 'Critical'
                              ? 'bg-rose-500/10 text-rose-300 border-rose-500/20'
                              : 'bg-amber-500/10 text-amber-300 border-amber-500/20'
                          }`}
                        >
                          {gap.importance}
                        </span>
                      </div>
                      {gap.azureEquivalent && (
                        <span className="text-xs text-sky-400 font-mono mt-1 block leading-relaxed">
                          Azure Service: {gap.azureEquivalent}
                        </span>
                      )}
                    </div>

                    <span className="text-xs font-extrabold text-emerald-400 font-mono shrink-0">
                      {gap.impactOnSalary}
                    </span>
                  </div>

                  <div className="pt-3 border-t border-[var(--border-color)] flex items-center justify-between text-xs text-[var(--text-muted)]">
                    <span className="truncate max-w-[280px] text-xs leading-relaxed">{gap.learningResource}</span>
                    <BookOpen className="w-4 h-4 text-sky-400 shrink-0" />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* 12-Week Learning Pathway */}
          <div className="saas-card p-8 rounded-3xl space-y-6">
            <div className="flex items-center gap-2.5 pb-3 border-b border-[var(--border-color)]">
              <Calendar className="w-5 h-5 text-sky-400" />
              <h3 className="text-base font-bold text-[var(--text-primary)] mb-1">
                12-Week Step-by-Step Accelerated Upskilling Pathway
              </h3>
            </div>

            <div className="space-y-5">
              {result.roadmap.map((phase, idx) => (
                <div
                  key={phase.phaseTitle}
                  className="p-6 rounded-2xl bg-[var(--bg-surface-subtle)] border border-[var(--border-color)] space-y-4 border-l-4 border-l-blue-500"
                >
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                    <span className="text-xs font-extrabold text-sky-400 font-mono">{phase.weekRange}</span>
                    <span className="text-xs text-[var(--text-muted)] font-bold">Milestone #{idx + 1}</span>
                  </div>

                  <div>
                    <h4 className="text-base font-bold text-[var(--text-primary)] mb-1">{phase.phaseTitle}</h4>
                    <p className="text-xs sm:text-sm text-[var(--text-secondary)] leading-relaxed mt-1">{phase.focus}</p>
                  </div>

                  <div className="p-4 rounded-xl bg-blue-500/10 border border-blue-500/20 text-xs space-y-1">
                    <span className="font-bold text-sky-300 block mb-1">Deliverable Capstone:</span>
                    <p className="text-[var(--text-primary)] font-mono text-xs leading-relaxed">{phase.deliverableProject}</p>
                  </div>

                  <div className="flex flex-wrap items-center gap-2 text-xs">
                    <span className="text-[var(--text-muted)] font-bold">Azure Services:</span>
                    {phase.azureResources.map(res => (
                      <span
                        key={res}
                        className="text-xs px-2.5 py-0.5 rounded-lg bg-[var(--bg-surface)] text-sky-400 border border-[var(--border-color)] font-medium"
                      >
                        {res}
                      </span>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
